### ISSUE TITLE
KeyError: "Key 'FFIINDEX' does not exist."

### ISSUE THREAD

**Issue by decaelus** [afeinstein20/eleanor#100]
Thanks for putting this package together. It's a huge help.

I'm running into some error which I don't understand. I run the following code in my jupyter notebook:

`star = eleanor.Source(tic=2758565, sector=2); data = eleanor.TargetData(star)`

and I get the exception in the subject line. I'm using python 3 and eleanor version 0.2.1. I've pasted a screencap of the error below. 

Thanks for your help.

<img width="866" alt="Screen Shot 2019-07-08 at 5 01 06 PM" src="https://user-images.githubusercontent.com/6087594/60848062-5a1af200-a1a2-11e9-9041-17c0f1b741b4.png">

**Comment by afeinstein20** [comment]
Hi @decaelus , Thanks for bringing this to our attention! Can you please try the following command:
star = eleanor.Source(tic=2758565, sector=2, **tc=True**) 
This should hopefully fix the issue. Let me know if it doesn't though and I'll look into it further!

**Comment by benmontet** [comment]
I agree with Adina. You've caught us right in the midst of upgrades to the postcard scheme/background modeling, which involves us sending some data over to STScI, and the code in the default setup is all set up for the new postcards before we've actually gotten them over there! tc=True gives a workaround that should give the performance of the current postcards with the latest software version. It's 100% my fault that's not included in the docs yet, it's on my to do list!
