### ISSUE TITLE
flux_bkg propagated through correctly when using tesscut frames

### ISSUE THREAD

**Issue by benmontet** [afeinstein20/eleanor#102]
I think it's being estimated correctly, but somewhere along the way it doesn't get stored in the dataproduct, or gets overwritten by zeroes before it's stored. Writing this down here so I remember to dig into it and track down why later!

**Comment by afeinstein20** [comment]
I think we might've solved this issue a while ago, since we were using TessCut for a long time?

**Comment by benmontet** [comment]
Yeah good call I just verified this is working properly now! Closing.
