### ISSUE TITLE
load_pointing_model fails

### ISSUE THREAD

**Issue by kareemelbadry** [afeinstein20/eleanor#107]
Hi, 

Thanks for making this code public!

I am trying to use the Visualize tools but get an error when calling 
vis = eleanor.Visualize(data). 

The error seems to originate with the function load_pointing_model() in ffi.py. Specifically, 
load_pointing_model(sector = 8, camera = 1, chip = 4)
produces a 404 error. The reason is that the invoked url,
https://users.flatironinstitute.org/dforeman/public_www/tess/postcards_test/s0008/pointing_model/pointingModel_0008_1-4.txt, does not exist. 

Perhaps this is just because Sector 8 isn't ready yet? But other aspects of eleanor seem to work fine for stars in this sector, so I wanted to check whether it's another issue.

**Comment by afeinstein20** [comment]
Hi @kareemelbadry Thanks for bringing this to our attention! What version of eleanor are you running?

**Comment by kareemelbadry** [comment]
Thanks for the quick response. version.py says __version__ = "0.2.1" (I pip installed about a month ago).

**Comment by afeinstein20** [comment]
Okay! We've had several updates since then, which may fix your issue. Please pip upgrade to **version = 0.2.4** and let me know if you still have the same issue as above.

**Comment by kareemelbadry** [comment]
Thanks. I upgraded to 0.2.4. However, the following code still produces a 404 error:

from eleanor import ffi 
ffi.load_pointing_model(sector = 8, camera = 1, chip = 4)

**Comment by afeinstein20** [comment]
Hi @kareemelbadry sorry for the super delayed response! We're currently working on creating all of the pointing models for each sector/camera/CCD. It wasn't working before because we did not have the files. They should hopefully be ready within the next few months!
