### ISSUE TITLE
problem creating custom rectangular aperture

### ISSUE THREAD

**Issue by bpablo** [afeinstein20/eleanor#108]
When trying to create a custom rectangular aperture using:

eleanor.TargetData.custom_aperture(data, shape='rectangle', w=width, l=length)

I keep getting the following error:

--> 887                 aperture = RectangularAperture(pos, l=l, w=w, t=theta)
    888                 self.aperture = aperture.to_mask(method=method)[0].to_image(shape=((
    889                             np.shape(self.tpf[0]))))

TypeError: __init__() got an unexpected keyword argument 'l'

**Comment by bpablo** [comment]
I found the issue. RectangularAperture in photutils takes "h" and not "l".

RectangularAperture(positions, w, h, theta=0.0)

Also I think the same issue will happen with the theta parameter. It should be "theta" and not "t".

**Comment by afeinstein20** [comment]
Hi @bpablo ! What version of photutils are you using? The latest version (v0.6) uses the parameters w, h, and theta, which is the version that eleanor is written to use. See the documentation here: https://photutils.readthedocs.io/en/stable/api/photutils.RectangularAperture.html

**Comment by bpablo** [comment]
Hey @afeinstein20. You're right photutils RectangularAperture uses w, h, and theta, but when eleanor calls this on line 908 of targetdata.py 

 else:
         aperture = RectangularAperture(pos, l=l, w=w, t=theta)
         self.aperture = aperture.to_mask(method=method)[0].to_image(shape=((
                   np.shape(self.tpf[0]))))            


it uses the variables "l" and "t" instead. Sorry, I didn't make my issue clearer. I changed the variables locally and it worked so that is the only issue.

**Comment by afeinstein20** [comment]
Oh, I see! Thanks for clarifying on the issue. I have fixed this and pushed it to the Github version. It will be fixed in the next version update :)
