### ISSUE TITLE
Clean up this package by removing scripts/functions only used in eleanor-tools

### ISSUE THREAD

**Issue by ethankruse** [afeinstein20/eleanor#109]
If eleanor-tools is going to be the active area of development for creating postcards and doing background estimation/subtraction, remove all the files in this repo that have been ported over there to avoid confusion and reduce clutter.  Likely candidates are make_background, make_postcards, make_guide (?), and the metadata folder (?).

**Comment by dfm** [comment]
As @ethankruse commented [on Twitter](https://twitter.com/ethan_kruse/status/1215805349376204800) this would also remove (at least!) fitstio from the dependencies for the main project.

**Comment by afeinstein20** [comment]
I removed make_background.py and make_postcards.py as well as the fitsio dependency (in addition to 2 more packages that are no longer being used).
