### ISSUE TITLE
Sector 13 targets not being found?

### ISSUE THREAD

**Issue by SimonJMurphy** [afeinstein20/eleanor#118]
I'm attempting to create a lightcurve with eleanor for a target observed only in sector 13. The TESScut tool finds this target with no problem. With eleanor I get an error:
```HD168947 = eleanor.Source(coords=(276.1252331,-44.1990942), sector=13, tc=True)```
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-e8a7267cd519> in <module>
----> 1 HD188164 = eleanor.Source(coords=(299.7207697,-68.7625833), sector=13, tc=True)

~/anaconda3/lib/python3.6/site-packages/eleanor/source.py in __init__(self, tic, gaia, coords, fn, sector, fn_dir, tc)
    189             if tc == True:
    190                 self.tesscut_size = 31
--> 191                 self.locate_with_tesscut() # sets sector, camera, chip, postcard,
    192                                   # position_on_chip, position_on_postcard
    193 

~/anaconda3/lib/python3.6/site-packages/eleanor/source.py in locate_with_tesscut(self)
    323         self.sector = self.usr_sec
    324 
--> 325         self.camera = sector_table[sector_table['sector'] == self.sector]['camera'].quantity[0]
    326         self.chip = sector_table[sector_table['sector'] == self.sector]['ccd'].quantity[0]
    327 

~/anaconda3/lib/python3.6/site-packages/astropy/units/quantity.py in __getitem__(self, key)
   1038     def __getitem__(self, key):
   1039         try:
-> 1040             out = super().__getitem__(key)
   1041         except IndexError:
   1042             # We want zero-dimensional Quantity objects to behave like scalars,

IndexError: index 0 is out of bounds for axis 0 with size 0
```

tess-waldo shows the target is in the middle of the CCD, so we're not dealing with any edge effects.

Behaviour is as expected for targets observed in Sector 13 _and_ earlier sectors. Only targets observed in sector 13 alone seem affected.

At this point, I'm pretty sure it's a look-up issue. Probably the maximum allowable index needs extending by 1 so that sector 13 can be accessed.

Interestingly, attempting to use eleanor.multi_sectors on such targets returns "Found star in Sector(s) [blank]".

**Comment by benmontet** [comment]
Hey,

What version of eleanor are you running? If it's not 0.2.7 could you please upgrade and try again? This call worked totally fine for me so you might be seeing some old bug that's since been fixed manifesting itself in some strange way.

**Comment by SimonJMurphy** [comment]
I was using 0.2.4, but I upgraded to 0.2.7 and confirmed with `print(eleanor.__version__)`. I'm still having this issue.

I'm very confused since you found this function call to work with no problems.

**Comment by afeinstein20** [comment]
Hi Simon, This is super weird! I have 3 things I'd like you to try:

- What version of[ tess-point](https://pypi.org/project/tess-point/) do you have on your machine? eleanor automatically downloads it. Unfortunately there's no tess_stars2px.__version__, so you'll have to go into wherever you download packages and check in the script :/ The good news is the version number is right at the top! If you don't currently have version 0.3.3, please update this. 

- If that doesn't work, could you please try passing your coordinates in as a SkyCoord object? In theory, this shouldn't make a difference. 

- And if all of that doesn't work, please delete your hidden .eleanor directory, which should be in your home directory. Sometimes there's a caching issue where dumping everything works.

Thanks :D

**Comment by benmontet** [comment]
Adina's suggestions are all good ones, and her #3 reminded me of another one for you to try: in addition to clearing your .eleanor directory, also please delete your Tesscut cache---if you've searched this star previously before sector 13 was available, it might be just using the old cached info rather than re-looking it up. This caused me issues before for a target I was investigating before sector 13 came out. For me this would mean deleting ~/.astropy/cache/astroquery/Tesscut/* but will be different for you if you've changed your astropy defaults!

**Comment by SimonJMurphy** [comment]
Thanks for the suggestions!
* I had tess-point 0.3.2, and just upgraded to 0.3.3. This didn't change the outcome (not working).
* I just tried passing in as a SkyCoord object. Alas, no dice.
* I have `rm -r`'d the `~/.eleanor/` directory, and still no dice. :(

**Comment by SimonJMurphy** [comment]
Bing, bing, bing! We have a winner!
Deleting the Tesscut cache did indeed fix the problem.
Evidently, my over-eagerness in trying to generate lightcurves for these targets before sector 13 was ingested has been my downfall.
Thank you both!

**Comment by afeinstein20** [comment]
🎉

**Comment by benmontet** [comment]
Great news!

The fine folks at MAST said recently they have designs on turning off auto-caching for Tesscut in a future astroquery upgrade so hopefully this won't happen in the future!
