### ISSUE TITLE
syntax error in tess_stars2px.py

### ISSUE THREAD

**Issue by MrBudgens** [afeinstein20/eleanor#124]
No characters at all are allowed after a line continuation, it seems, so "import eleanor" fails because of the comments here:

File ".../Anaconda3/lib/site-packages/tess_point-0.3.4-py3.7.egg/tess_stars2px.py", line 730
    ras = np.array([352.6844,16.5571,36.3138,55.0070,73.5382, \ #S1-5
                                                                     ^
SyntaxError: unexpected character after line continuation character

**Comment by afeinstein20** [comment]
Thanks for bringing this to our attention! We have submitted a pull request to fix this issue on tess-point. If you download tess-point version==0.3.3, this should no longer be an issue for now. If this doesn't solve it, please feel free to re-open this issue. Thanks!

**Comment by MrBudgens** [comment]
Thank you, your now-accepted pull request has solved the problem.
