### ISSUE TITLE
Source.py::tesscut_dir() needs to test for the need to os.mkdir $HOMEDIR/.eleanor 

### ISSUE THREAD

**Issue by texadactyl** [afeinstein20/eleanor#125]
Running the quickstart sample .....
```
import eleanor
import numpy as np
import matplotlib.pyplot as plt

star = eleanor.Source(tic=38846515, sector=1, tc=True)
```
gets the following error:
```
source.py:396: UserWarning: Warning: unable to create .. Downloading TessCut to the current working directory instead.
  'working directory instead.'.format(download_dir))
```
In ```Source.py::tesscut_dir()``` the download directory is implicitly created as follows at line 396:
```
download_dir = os.path.join(os.path.expanduser('~'), '.eleanor/tesscut')
```
If directory $HOMEDIR/.eleanor does not yet exist, it must be created (```os.mkdir```) before executing that statement.  Otherwise, the downloaded file winds up in the current directory (not desirable).

Running on Xubuntu 18.04.3.latest with Python 3.latest.

**Comment by texadactyl** [comment]
Something simple like this would work:
```
from os.path import expanduser
DIR = expanduser("~/.eleanor")
if not os.path.exists(DIR):
    try:
        os.mkdir(DATA_DIR)
    except Exception as err:
        oops("main: Cannot create directory {}:\n{}".format(DIR, str(err)))
```

**Comment by texadactyl** [comment]
For whatever it is worth, I just ran into a surprising tensorflow fatal anomaly (not an eleanor issue).
See https://github.com/tensorflow/tensorflow/issues/17411 for description and ugly work-around.

A one-line program produces it:
```
import tensorflow as tf
```
like in ```targetdata.py::psf_lightcurve()```

**Comment by benmontet** [comment]
This should be sorted in the most recent version 1.0.0, thanks for pointing it out!
