### ISSUE TITLE
problem creating custom rectangular aperture

### ISSUE THREAD

**Issue by hvidy** [afeinstein20/eleanor#128]
When trying to create a custom rectangular aperture using
`eleanor.TargetData.custom_aperture(data, shape='rectangle', h=height, w=width)`

we are getting an error thrown by line 924 of targetdata.py:
`NameError: name 'l' is not defined`

It seems on line 924 of targetdata.py that `l==0.0` should be `h==0.0`.
Would also expect that line 927 will give the same error and that there, `h=l` should be `h=h`.

**Comment by afeinstein20** [comment]
Hi @hvidy Thanks for pointing this out! The issue has been fixed and pushed to the latest version of eleanor on Github :)
