### ISSUE TITLE
tess_stars2px

### ISSUE THREAD

**Issue by benjaminpope** [afeinstein20/eleanor#130]
Hi Adina,

Getting a new bug in eleanor==0.2.9: 

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-240b7ed14e42> in <module>()
      6 from lightkurve import TessTargetPixelFile, TessLightCurveFile, TessLightCurve
      7 
----> 8 import eleanor
      9 
     10 

2 frames
/content/eleanor/eleanor/source.py in <module>()
      8 import sys
      9 from os.path import join, abspath
---> 10 from tess_stars2px import tess_stars2px_function_entry as tess_stars2px
     11 import warnings
     12 from astroquery.mast import Tesscut

ModuleNotFoundError: No module named 'tess_stars2px'
`

**Comment by afeinstein20** [comment]
Hey @benjaminpope This seems like an issue with tess-point. It's included in the eleanor setup.py file, so if you ran/run that it should be somewhere on your machine. Can you make sure it installed somewhere in your library path?

**Comment by benjaminpope** [comment]
Thanks, that fixed it!
