### ISSUE TITLE
Importing eleanor breaks astroquery

### ISSUE THREAD

**Issue by nksaunders** [afeinstein20/eleanor#136]
Oh boy I spent so long trying to figure this one out. After importing `eleanor`,  `astroquery` returned nothing for some (but not all) FFI targets. This only happens if `eleanor` is imported in the same kernel. 

Here's the problem — when `eleanor` is imported, it overwrites the `astroquery` url strings. This happens in `eleanor/source.py` in these lines:

```python 
server = "https://masttest.stsci.edu"
Observations._MAST_REQUEST_URL = server + "/portal_eleanor/Mashup/MashupQuery.asmx/invoke"
Observations._COLUMNS_CONFIG_URL = server + "/portal_eleanor/Mashup/Mashup.asmx/columnsconfig"
Observations._MAST_DOWNLOAD_URL = server + "/api/v0.1/download/file"
```

After those variables are overwritten, `astroquery` searches the wrong url for data products. A minimal working example is shown below.

<img width="1085" alt="Screen Shot 2019-11-22 at 3 06 17 PM" src="https://user-images.githubusercontent.com/17130840/69470295-aa51b580-0d39-11ea-9245-04f74b326b62.png">

I suggest we store the default values of the urls and make sure `eleanor` switches them back after downloading files.

Thank you @barentsen for helping me figure out what was going wrong!

**Comment by afeinstein20** [comment]
I commented these out for now haha thanks for pointing it out!
