### ISSUE TITLE
issue loading in a previously saved eleanor FITS file

### ISSUE THREAD

**Issue by benmontet** [afeinstein20/eleanor#137]
Something weird is going on with it being unable to find the postcard header in targetdata (post_obj.header). This is the case when using a previously-saved FITS file and when local is set to be true. I'll dig into what's going on, but this is a fairly specific use case so it's not high on my priority list.

**Comment by orionlee** [comment]
I think I encountered the same problem. Details:
```python
    tic, sector = 394346745, 12
    star = eleanor.Source(tic=tic, sector=sector, tc=True)
    datum = eleanor.TargetData(star, height=13, width=13, bkg_size=31, do_psf=False, do_pca=False)
    datum.save()
    
    datum_loaded = eleanor.TargetData(source=eleanor.Source(local=True, tc=True, fn='hlsp_eleanor_tess_ffi_tic394346745_s12_tess_v2.0.0_lc.fits'))
```

Error:
```python
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-20d177cfb068> in <module>()
----> 5 datum_loaded = eleanor.TargetData(source=eleanor.Source(local=True, tc=True, fn='hlsp_eleanor_tess_ffi_tic394346745_s12_tess_v2.0.0_lc.fits'))
      6 datum_loaded
      7 

C:\pkg\_winNonPortables\Anaconda3\envs\Pyriod\lib\site-packages\eleanor\source.py in __init__(self, tic, gaia, coords, name, fn, sector, fn_dir, tc, local, post_dir, pm_dir, metadata_path, tesscut_size)
    201                 post_dir = self.tesscut_dir()
    202                 self.postcard_path = os.path.join(post_dir, self.postcard)
--> 203                 self.cutout = fits.open(self.postcard_path)
    204 #            else:
    205                 #########
...
...

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SL\\.eleanor/tesscut\\tesscut\\tess-s0012-3-4_42.888115_-81.007046_31x31_astrocut.fits'
```

**Version:** 2.0.0
Platform: Windows

**Comment by orionlee** [comment]
For the specific problem I encountered: https://github.com/afeinstein20/eleanor/blob/bd5b8cdc6d80bda9ebab2b464f07aab24bc93f7f/eleanor/source.py#L200-L203

- `self.postcard`, the `POSTCARD` header in the FITS file generated from `save()`, contains `tesscut` prefix in its content, e.g., `tesscut\\tess-s0012-3-4_42.888115_-81.007046_31x31_astrocut.fits` in the example above.
- the resulting postcard_path in line 202 has two `tesscut` in its path as a result.

A workaround is to correct the `postcard_path` generated:
```python
                import re
                self.postcard_path = re.sub(r'tesscut[/\\]tesscut', 'tesscut', self.postcard_path)  # workaround to address #137
                self.cutout = fits.open(self.postcard_path)
```

A proper fix might involve changing the `POSTCARD` header during `save()`. But a workaround similar to above would still be needed to handle the FITS files that have been generated.
