### ISSUE TITLE
bug in targetdata.get_lightcurve()

### ISSUE THREAD

**Issue by kareemelbadry** [afeinstein20/eleanor#140]
Line 567 of targetdata.py reads:

`all_lc_err[a] = np.sqrt( np.nansum(self.tpf_err**2 * self.all_apertures[a]) )`

The np.nansum sums over the whole array of times, instead of summing over pixels at each time. The end result is that data.flux_err ends up being too large, and being the same at all cadences.  I think  the line should be replaced with

`all_lc_err[a] = np.sqrt( np.nansum(self.tpf_err**2 * self.all_apertures[a], axis=(1,2)  )`

**Comment by benmontet** [comment]
Yes I do believe you're correct! I've updated the line and am going to close this issue---if you notice any odd behavior as a result of this change please do reopen it. Thanks for pointing this out!
