### ISSUE TITLE
MAST Gateway Error via eleanor

### ISSUE THREAD

**Issue by rachelbf** [afeinstein20/eleanor#145]
I have the latest version of eleanor. I started getting a 504 gateway error like this on several of my targets (but not all) since earlier this morning. 
<img width="1289" alt="Screen Shot 2020-01-15 at 11 59 13" src="https://user-images.githubusercontent.com/48811452/72466807-7b325000-378e-11ea-9ef7-f445247f6408.png">

**Comment by benmontet** [comment]
This means calls to MAST to download FFI cutouts through TESScut are timing out. TESSCut often struggles while they are ingesting new data, or if it persists for more than a day or two, the issue could be with your internet. 

If these are targets in sectors 0001-0013, I would recommend not using the tc=True call and avoiding the call to tesscut.
