### ISSUE TITLE
TessCut + cadences

### ISSUE THREAD

**Issue by afeinstein20** [afeinstein20/eleanor#147]
Using TessCut for sectors in the northern hemisphere doesn't create the metadata behind the scenes?

`stars = eleanor.multi_sectors(tic=tic, sectors='all')

data = []

for star in stars:
    datum = eleanor.TargetData(star)
    data.append(datum)`

Issue:

`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-3699b290b08b> in <module>
      2 
      3 for star in stars:
----> 4     datum = eleanor.TargetData(star)
      5     data.append(datum)

//anaconda3/lib/python3.7/site-packages/eleanor/targetdata.py in __init__(self, source, height, width, save_postcard, do_pca, do_psf, bkg_size, crowded_field, cal_cadences, try_load, language)
    171                     self.post_obj = Postcard_tesscut(source.cutout)
    172 
--> 173                 self.ffiindex = self.post_obj.ffiindex
    174                 self.flux_bkg = self.post_obj.bkg
    175                 self.get_time(source.coords)

//anaconda3/lib/python3.7/site-packages/eleanor/postcard.py in ffiindex(self)
    349         sector = self.header['SECTOR']
    350         eleanorpath = os.path.join(os.path.expanduser('~'), '.eleanor')
--> 351         A = np.loadtxt(eleanorpath + '/metadata/s{0:04d}/cadences_s{0:04d}.txt'.format(sector))
    352         return A
    353 

//anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows)
    960             fname = os_fspath(fname)
    961         if _is_string_like(fname):
--> 962             fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
    963             fencoding = getattr(fh, 'encoding', 'latin1')
    964             fh = iter(fh)

//anaconda3/lib/python3.7/site-packages/numpy/lib/_datasource.py in open(path, mode, destpath, encoding, newline)
    264 
    265     ds = DataSource(destpath)
--> 266     return ds.open(path, mode, encoding=encoding, newline=newline)
    267 
    268 

//anaconda3/lib/python3.7/site-packages/numpy/lib/_datasource.py in open(self, path, mode, encoding, newline)
    622                                       encoding=encoding, newline=newline)
    623         else:
--> 624             raise IOError("%s not found." % path)
    625 
    626 

OSError: /Users/arcticfox/.eleanor/metadata/s0015/cadences_s0015.txt not found.`

(This is a reminder to look into this Monday/Tuesday)

**Comment by benmontet** [comment]
Issue #142 just had the same experience. It should work fine as long as you don't already have a partial ~/.eleanor/metadata/s00xx directory, as it checks if that exists and then runs the update script. (There are probably better ways to do this, to check on a file-by-file basis if it needs to make anything). Do you have that metadata/s0015 directory already? If so that would explain it (but we have to figure out what is making that directory and leaving it and getting the rest of the software confused...)
