### ISSUE TITLE
This call to load_pointing_model will now fail with the rewrite of the function

### ISSUE THREAD

**Issue by ethankruse** [afeinstein20/eleanor#149]
https://github.com/afeinstein20/eleanor/blob/e5e4e31333a6aad68168a78ac505a8b83d8ae944/eleanor/ffi.py#L88-L89

`load_pointing_model` now assumes there are 4 arguments and that the first will be a directory.

I don't know how to fix this, because I think this requires some interfacing with eleanor-tools, since I think that's the only place this function is called. And TBH, I think in eleanor-tools, you're always supposed to already have the pointing model loaded, so this line *should* never be executed and you can probably replace the function call with raising an Exception.

**Comment by benmontet** [comment]
Changed as per #153

**Comment by ethankruse** [comment]
Thanks Ben. Can you take a look at the PR #148 that deals with the check_pointing calls as well when you get a chance? Dunno if you missed that one since it's a PR not an issue or if it's just lower on your to-do list. That's the one that was causing problems for our local stuff.

**Comment by benmontet** [comment]
Yeah I'm aware of it and it's on my list, I have limited research time to serve as a helpdesk in a given week and code review is a slow process. Will get to it.
