### ISSUE TITLE
Not all sectors from TESScut are being found

### ISSUE THREAD

**Issue by SimonJMurphy** [afeinstein20/eleanor#150]
I'm attempting to create a lightcurve with eleanor for a target observed in sectors 9 and 10. Both the TESS web view tool and TESScut find both sectors for this target with no problem. With eleanor I only see sector 9 when using multi_sectors:

`HD88554 = eleanor.multi_sectors(coords=(153.0620783,-24.9128065), sectors='all', tc=True)`

> Found star in Sector(s) 9

Using .Source on sector 10 failed:

`HD88554_s10 = eleanor.Source(coords=(153.0620783,-24.9128065), sector=10, tc=True)`

> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-9-f4fbfd1f2a89> in <module>
> ----> 1 HD88554_10 = eleanor.Source(coords=(153.0620783,-24.9128065), sector=10, tc=True)
> 
> ~/anaconda3/lib/python3.6/site-packages/eleanor/source.py in __init__(self, tic, gaia, coords, fn, sector, fn_dir, tc, local, post_dir, pm_dir)
>     215                 self.tess_mag = self.tess_mag[0]
>     216 
> --> 217             self.locate_on_tess()
>     218             self.tesscut_size = 31
>     219 
> 
> ~/anaconda3/lib/python3.6/site-packages/eleanor/source.py in locate_on_tess(self)
>     261             # Handles cases where users can pass in their sector
>     262             if type(self.usr_sec) == int:
> --> 263                 arg = np.argwhere(sectors == self.usr_sec)[0]
>     264                 if len(arg) > 0:
>     265                     self.sector = sectors[arg][0]
> 
> IndexError: index 0 is out of bounds for axis 0 with size 0

Things I have tried so far:
- pip install tess-point --upgrade
- passing as a SkyCoord object
- rm -r ~/.eleanor/*
- rm ~/.astropy/cache/astroquery/Tesscut/*
- restarting the python kernel and re-running.
- posting this new issue on github.

Eleanor version is 1.0.2.

Please help. You're my only hope.

**Comment by benmontet** [comment]
Hey,

I can look into this, it sure beats working on a grant!

HD 88854 has different coordinates than the coords you're passing through. Is that just a mislabeled variable for the starname, or is it possible these coords are incorrect?

**Comment by SimonJMurphy** [comment]
Hah, how about that. The coordinates were totally wrong.
I should have a caffeine lock on my laptop that doesn't let me copy-paste before 1 coffee, lest a copy-paste fail run me in circles later in the day.
Good spot, Ben!

**Comment by benmontet** [comment]
Great news!

Also see #151 which @afeinstein20 just closed---if you download the most recent commit from github you will be able to pass through a name that will get resolved, so ```eleanor.multi_sectors(name="HD 88554") should in principle get you what you need!

**Comment by afeinstein20** [comment]
you stole my thunder @benmontet 
<img width="764" alt="Screen Shot 2020-01-22 at 10 04 43 PM" src="https://user-images.githubusercontent.com/5041100/72955865-3779b080-3d63-11ea-9854-f1591b21a99b.png">

**Comment by SimonJMurphy** [comment]
![image](https://user-images.githubusercontent.com/509713/72955985-3479d100-3df2-11ea-8213-cfc3f8eb8c4e.png)

**Comment by benmontet** [comment]
Oh I'm not sure if it's a good career move for you for people to know that we think alike! 😉
