### ISSUE TITLE
Allow users to push a target name through to Source

### ISSUE THREAD

**Issue by benmontet** [afeinstein20/eleanor#151]
SJM's issue makes me realize if someone doesn't know the TIC or coords or Gaia (maybe they have an HD number) they need to look up one or more of those. It would be cool if we could use astroquery to resolve coords if someone gave a name into eleanor.Source()

I think it would be easy!

>>> from astroquery.simbad import Simbad
>>> result_table = Simbad.query_object("M1")

will give coordinates for M1, and then we can just set those as source.coords and everything else will flow from there. 

But I don't want to do it myself right now so I'm going to leave it as an issue so I remember later.

**Comment by afeinstein20** [comment]
I'm not going to say that I implemented this because that would admit to working at 10pm, but also I implemented this and pushed the changes so I'm closing the issue....

**Comment by benmontet** [comment]
I'm not going to say 'nice!' and condone you working at 10pm, but also nice!
