### ISSUE TITLE
testing eleanor with quickstart tutorial fails

### ISSUE THREAD

**Issue by vtkovacs** [afeinstein20/eleanor#152]
I am installing eleanor at Dartmouth College and running through the tutorial as a test of success.
All is well until I get to this step:
In [11]: data = eleanor.TargetData(star, height=15, width=15, bkg_size=31, do_psf=True, do_pca=True) 

Please see eleanor.fail.txt  for more information.
Thanks - Terry
[eleanor.fail.txt](https://github.com/afeinstein20/eleanor/files/4103983/eleanor.fail.txt)

**Comment by vtkovacs** [comment]
Updating all python packages eliminated the issue with downloading finals2000A.all but it still ends badly with "LinAlgError: Singular matrix"

**Comment by vtkovacs** [comment]
Issue resolved.  I deleted .eleanor and .astropy in $HOME and the problem is no longer!

**Comment by benmontet** [comment]
Hey, thanks for posting what solved the issue for you! This seems like it's the same issue as #142 which we've been struggling to reproduce over here and thus fix, so knowing what worked for you is extremely helpful!
