### ISSUE TITLE
Eleanor not returning all sectors

### ISSUE THREAD

**Issue by MarcoMuellner** [afeinstein20/eleanor#156]
Hello!

I have a bit of an issue with the returned data from eleanor. Looking at MAST, for the star _ET Cha_ there are 4 sectors worth of observation. This is also returned when directly querying MAST using astroquery:
```python
from astroquery.mast import Observations
import astropy.units as u

Observations.query_criteria(objectname="ET Cha", radius=str(0 * u.deg), project='TESS',
                                        obs_collection='TESS')
```
returns 
```
Out[3]: 
<Table masked=True length=4>
dataproduct_type calib_level obs_collection ...    objID       objID1   distance
      str5          int64         str4      ...    str11       str11    float64 
---------------- ----------- -------------- ... ----------- ----------- --------
           image           3           TESS ... 17003534924 17003534924      0.0
           image           3           TESS ... 17003534971 17003534971      0.0
           image           3           TESS ... 17003535018 17003535018      0.0
           image           3           TESS ... 17003535066 17003535066      0.0
```

If i look at this star using eleanor using
```python
import eleanor
eleanor.multi_sectors(sectors='all',name='ET Cha',tc=True)
```
 i get the following result:
```
Found star in Sector(s) 11 12 13
Out[6]: 
[<eleanor.source.Source at 0x1083eeeb8>,
 <eleanor.source.Source at 0x1192d66d8>,
 <eleanor.source.Source at 0x108ca3b00>]
```

which is missing sector 10 for this star. I think this kind of relates to #150 ?

Any idea why this happens?

Cheers,
Marco

**Comment by MarcoMuellner** [comment]
Oh one more thing, which is probably unrelated to eleanor and more to astroquery. Using the tic id for mast.Observations results in an error (this is rather new, worked yesterday perfectly). The following snippet would cause the error:

```python
from astroquery.mast import Observations
import astropy.units as u

Observations.query_criteria(objectname="TIC 323292671", radius=str(0 * u.deg), project='TESS',
                                        obs_collection='TESS')
```
This results in the following:
```
---------------------------------------------------------------------------
ResolverError                             Traceback (most recent call last)
<ipython-input-7-5c9fc9040b2c> in <module>
      1 Observations.query_criteria(objectname="TIC 323292671", radius=str(0 * u.deg), project='TESS',
----> 2                                         obs_collection='TESS')

~/Documents/Dev/science/eleanor/venv/lib/python3.6/site-packages/astroquery/utils/class_or_instance.py in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

~/Documents/Dev/science/eleanor/venv/lib/python3.6/site-packages/astroquery/utils/process_asyncs.py in newmethod(self, *args, **kwargs)
     24             verbose = kwargs.pop('verbose', False)
     25 
---> 26             response = getattr(self, async_method_name)(*args, **kwargs)
     27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28                 return response

~/Documents/Dev/science/eleanor/venv/lib/python3.6/site-packages/astroquery/utils/class_or_instance.py in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

~/Documents/Dev/science/eleanor/venv/lib/python3.6/site-packages/astroquery/mast/core.py in query_criteria_async(self, pagesize, page, **criteria)
   1250 
   1251         if objectname:
-> 1252             coordinates = self.resolve_object(objectname)
   1253 
   1254         if coordinates:

~/Documents/Dev/science/eleanor/venv/lib/python3.6/site-packages/astroquery/mast/core.py in resolve_object(self, objectname)
    857 
    858         if len(result['resolvedCoordinate']) == 0:
--> 859             raise ResolverError("Could not resolve {} to a sky position.".format(objectname))
    860 
    861         ra = result['resolvedCoordinate'][0]['ra']

ResolverError: Could not resolve TIC 323292671 to a sky position.
```
Due to the fact that eleanor uses astroquery to resolve the coords if you provide a tic id, you get the same error:

```python
import eleanor
eleanor.multi_sectors(sectors='all',tic=323292671,tc=True)
```
results in a astroquery.exceptions.ResolveError exception:
```
Traceback (most recent call last):
  File "/Users/marco/Documents/Dev/science/smurf/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-66a5ec96b389>", line 1, in <module>
    eleanor.multi_sectors(sectors='all',tic=323292671,tc=True)
  File "/Users/marco/Documents/Dev/science/smurf/venv/lib/python3.6/site-packages/eleanor_mamu-1.0.2-py3.6.egg/eleanor/source.py", line 50, in multi_sectors
    coords, _, _, _ = coords_from_tic(tic)
  File "/Users/marco/Documents/Dev/science/smurf/venv/lib/python3.6/site-packages/eleanor_mamu-1.0.2-py3.6.egg/eleanor/mast.py", line 151, in coords_from_tic
    ticData = Catalogs.query_object('tic'+str(tic), radius=.0001, catalog="TIC")
  File "/Users/marco/Documents/Dev/science/smurf/venv/lib/python3.6/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/Users/marco/Documents/Dev/science/smurf/venv/lib/python3.6/site-packages/astroquery/utils/process_asyncs.py", line 26, in newmethod
    response = getattr(self, async_method_name)(*args, **kwargs)
  File "/Users/marco/Documents/Dev/science/smurf/venv/lib/python3.6/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/Users/marco/Documents/Dev/science/smurf/venv/lib/python3.6/site-packages/astroquery/mast/core.py", line 2051, in query_object_async
    coordinates = self.resolve_object(objectname)
  File "/Users/marco/Documents/Dev/science/smurf/venv/lib/python3.6/site-packages/astroquery/mast/core.py", line 859, in resolve_object
    raise ResolverError("Could not resolve {} to a sky position.".format(objectname))
astroquery.exceptions.ResolverError: Could not resolve tic323292671 to a sky position.
```

**Comment by benmontet** [comment]
Hi @MarcoMuellner! The second one is indeed an issue that MAST is having right now. You'll find if you go to the MAST portal and try to search for the same TIC it also will not be in there. MAST is aware and believes they will fix that soon. For now, passing through coordinates will definitely work and object names should as well, I think.

We'll look into your first issue tomorrow. Do you know, was the star definitely observed in Sector 10? Astroquery sometimes returns things as on silicon that are in truth a couple pixels off the edge of the detector, which may be the case here.

**Comment by MarcoMuellner** [comment]
Hey Ben!
I thought as much, thanks for the confirmation. Can you point me to some message from MAST where they state as much? I can't seem to find anything on their homepage or on Twitter for that matter.

As for the missing sector: I checked, and i can download the proper cutout from TESScutout and have a look at it in jupyter:

```python
from lightkurve import search_tesscut
tpf = search_tesscut("ET Cha",sector=10).download()
tpf.interact()
```
Also when looking at TASOC, the star seems to be on the lower right corner of the CCD, but still clearly on the CCD, so i think it should have been observed. The star is also listed in MAST as observed in sector 10.

Thanks for the quick reply!

**Comment by afeinstein20** [comment]
Hi @MarcoMuellner I've received word that the MAST name resolver issue should be fixed by now! As for the other issue where eleanor isn't downloading your source, we're going to look into that today :) thanks!

**Comment by benmontet** [comment]
Okay, looking into the first part---for sector 10, the star does fall on the CCD, at x=6 and y=4. However, the first 44 columns are "serial register columns" on the CCD and aren't actually exposed to starlight. So there's a pixel there when you map the entire detector frame onto the sky, but those pixels just have noise around zero. When I pull up the TESSCut cutout I just get noise, no real usable data. 

eleanor is smart about these cases and doesn't return them, which is why you're only getting three sectors from our software, while the other software returns data if there are some pixels there, even if they're not recording any astrophysics.

I think that sorts everything, so I'm going to close the issue; if you think we're missing something over here please do feel free to re-open it!

**Comment by MarcoMuellner** [comment]
Hi Ben, thanks for clearing up my confusion!

Would it be possible to add a little statement when running eleanor, that a given sector isn't available? This would help further confusion down the line ...
