### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by Dishendramishra** [afeinstein20/eleanor#157]
Code Snippet

```python
from IPython.display import Image

import eleanor
import numpy as np
from astropy import units as u
import matplotlib.pyplot as plt
from astropy.coordinates import SkyCoord

star = eleanor.Source(tic=38846515, sector=1)

print('Found TIC {0} (Gaia {1}), with TESS magnitude {2}, RA {3}, and Dec {4}'
     .format(star.tic, star.gaia, star.tess_mag, star.coords[0], star.coords[1]))
```

Output:
```
Traceback (most recent call last):
  File "temp.py", line 9, in <module>
    star = eleanor.Source(tic=38846515, sector=1)
  File "C:\Users\dishendra\AppData\Local\Programs\Python\Python36\lib\site-packages\eleanor\source.py", line 217, in __init__
    self.locate_on_tess()
  File "C:\Users\dishendra\AppData\Local\Programs\Python\Python36\lib\site-packages\eleanor\source.py", line 249, in locate_on_tess
    result = tess_stars2px(6789998212, self.coords[0], self.coords[1])
  File "C:\Users\dishendra\AppData\Local\Programs\Python\Python36\lib\site-packages\tess_stars2px.py", line 1014, in tess_stars2px_function_entry
    outID[0] = curTarg.ticid
OverflowError: Python int too large to convert to C long
```

While trying the example from the quick-start guide (from here [documentation](http://adina.feinste.in/eleanor/getting_started/tutorial.html)) I ran into the above error. I didn't understand what gone wrong.

**Comment by afeinstein20** [comment]
Hi @Dishendramishra Can you please update tess-point and try again? I think this might be the issue.

**Comment by Dishendramishra** [comment]
```shell
shendra@mac: ~ » pip3 show tess-point                                                   [16:02:24]
Name: tess-point
Version: 0.3.9
Summary: Determine pixel coordinates for TESS targets
Home-page: https://github.com/christopherburke/tess-point
Author: Christopher J. Burke
Author-email: cjburke@mit.edu
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires: astropy, scipy, numpy
Required-by: eleanor
```

Hi @afeinstein2, I am using the latest version of tess-point. 

> Hi @Dishendramishra Can you please update tess-point and try again? I think this might be the issue.

**Comment by benmontet** [comment]
Hi @Dishendramishra, what OS are you using? Is it a windows machine perhaps? I think this might be an issue with the way numpy stores "int" when one is using a 32-bit windows machine.

**Comment by LT25** [comment]
I am running into this same issue. I am running 64-bit Windows and 64-bit python.

**Comment by Dishendramishra** [comment]
```shell
pip install eleanor-mamu
```
this module works fine on linux

**Comment by Leilei-astro** [comment]
I have the same issue that occur when running on Windows 64 system, How do you solve the above issue? 
code:
`import eleanor
import numpy as np

star = eleanor . Source ( tic =468240308 , sector =1)`
the last four rows output:
`
  File "D:\Anaconda\lib\site-packages\tess_stars2px.py", line 1015, in tess_stars2px_function_entry
    outID[0] = curTarg.ticid

OverflowError: Python int too large to convert to C long`

**Comment by benmontet** [comment]
Hi folks,

The issue with this is coming from the tess-point dependence and the way windows deals C longs (in that they are always 32 bit on windows, even with a 64-bit python). We've looped in the developer of that package and once it's sorted we will update the version requirements inside of eleanor to require that latest version. Until then because eleanor depends on tess-point it will not work on Windows, so if you can access a unix-based architecture for the moment I would recommend that.

**Comment by benmontet** [comment]
Okay, I believe this may be sorted through tess-point now. Can you please upgrade tess-point to the latest version, 0.4.1, and try again?

**Comment by Dishendramishra** [comment]
> Okay, I believe this may be sorted through tess-point now. Can you please upgrade tess-point to the latest version, 0.4.1, and try again?

![image](https://user-images.githubusercontent.com/6905938/78211228-fec82700-74c9-11ea-97a6-fc8b1cb256a9.png)


![image](https://user-images.githubusercontent.com/6905938/78211144-d0e2e280-74c9-11ea-9b49-5a5c105e2a30.png)

Yes, it is working now.
