### ISSUE TITLE
Inaacurate Light Curve Generation after installation.

### ISSUE THREAD

**Issue by AstroNeel98** [afeinstein20/eleanor#171]
I am New to Eleanor, and post installation I tried generating the light curve for the object WASP-100 that has been provided in the example, using almost identical script. The Light Curve generated is very different from that shown on the MAST website as well as the one shown in the Eleanor web page.

```
# import warnings
# warnings.filterwarnings('ignore')

import eleanor
import numpy as np
from astropy import units as u
import matplotlib.pyplot as plt
from astropy.coordinates import SkyCoord


star = eleanor.Source(tic=38846515, sector=1)

print('Found TIC {0} (Gaia {1}), with TESS magnitude {2}, RA {3}, and Dec {4}'
     .format(star.tic, star.gaia, star.tess_mag, star.coords[0], star.coords[1]))


data = eleanor.TargetData(star, height=15, width=15, bkg_size=31, do_psf=True, do_pca=True)
print((data))
plt.figure(figsize=(15,5))

q = data.quality == 0

plt.plot(data.time[q], data.raw_flux[q]/np.nanmedian(data.raw_flux[q])+0.06, Marker = 'o', Color = 'k')
plt.plot(data.time[q], data.corr_flux[q]/np.nanmedian(data.corr_flux[q]) + 0.03, Marker = 'o',Color = 'r')
# plt.plot(data.time[q], data.pca_flux[q]/np.nanmedian(data.pca_flux[q]), 'g')
# plt.plot(data.time[q], data.psf_flux[q]/np.nanmedian(data.psf_flux[q]) - 0.02, 'b')
plt.ylabel('Normalized Flux')
plt.xlabel('Time [BJD - 2457000]')
plt.grid()
plt.show()

```
While first Run of the code after installation I encountered the following error :
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'tess2018206045859-s0001-4-4-0120-s_cbv.fits'

The entire program log is in the text file attached.
[First Run.txt](https://github.com/afeinstein20/eleanor/files/4516327/First.Run.txt)

However, in the second run of the program I was able to generate light curves corresponding to the raw data and the corr. data but they were highly inaccurate. The PCF curve appeared like a delta function, and Psf curve has no data.

Also there was an error related to the object going out of the FFI of Tess postcard. The program Log for the second Run is as attached here :- 

[Run2.txt](https://github.com/afeinstein20/eleanor/files/4516383/Run2.txt)

While the  expected plot was the following : 
![getting_started_tutorial_12_0](https://user-images.githubusercontent.com/64145594/79988590-7509e900-84cc-11ea-96b4-fbcd5e988278.png)

What actually is generated is something like this : 

![Figure_1](https://user-images.githubusercontent.com/64145594/79988722-966ad500-84cc-11ea-991f-073151e61c41.png)

The PCA curve disturbs the entire plot hence I have not plotted it.

**Comment by benmontet** [comment]
I don't have a Windows machine to test everything, but this seems related to file I/O somehow. Do you have access to another machine to compare against? 

I think it's not finding the pointing model properly, so it's finding the wrong pixels to search. That would jive with the 'your target might fall off the postcard' warning.

Once you define star, can you print the pointing model? It's saved as `star.pointing`. It should be an array of size (1282, 9) for the example you're working through,  and if you reshaped the 9 as a 3x3 matrix it should be something close to 

`1 0 0`
`0 1 0`
`-1 -1 1`

Specifically for the very final row you should get:

```print(star.pointing[-1].as_void)```

```0.9999596359856762 6.008149157113267e-05 4.0991388248558577e-19 8.714018857627337e-05 0.9999868047607952 -2.1849051656734444e-19 -1.0414253725236766 -1.036551762939438 1.000000000000002```

If it's different, then that's an issue that I think is related to what you're seeing!

**Comment by AstroNeel98** [comment]
I have tried this on 3 different Windows PC and all of them are showing me the same result. while I tried printing the pointing model, instead of the said array of (1282,9), I am getting a None object as output.
 I am using PyCharm to run the script. I had inserted `print(star.pointing)` after line 12 of the original code. While using the command `print(star.pointing[-1].as_void)`  gives me a type error as follows 

  ```
  print(star.pointing[-1].as_void)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by benmontet** [comment]
Yes okay so it's not reading in the pointing model correctly. I would check that `star.pm_dir` is properly set and that the pointing model in that directory looks fine. If that directory has an ascii file with the pointing model and that's fine, the bug must be somewhere in how windows machines are working with the `check_pointing` function in eleanor/ffi.py, and I would be keen to know the values of all the variables in that function immediately after they're set! Once that gets and loads in the right file, you'll have this problem sorted.

**Comment by AstroNeel98** [comment]
The command `star.pim_dir` points to .elanor folder in the C:/Users/NeelVadodaria. It contains ASCII files divided in two folders mastDownload and metadata. There ascii and fits files of the postcard. However I cannot a file with Pointing Model in it, or something that goes by that name.

**Comment by benmontet** [comment]
Okay, your run2.txt file shows that it's downloading to

\Users\NEEL VADODARIA\.eleanor/mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0001-4-1_tess_v2_pm.txt

Does that file exist in that directory?

If it does, after your call to eleanor.Source() but before your call to eleanor.TargetData() can you set star.pm_dir to be that directory manually and see if that works. I'm not sure why it's not finding it correctly, but it may be the windows vs unix structure of using backslashes vs forward slashes.

If it does not, then delete that entire directory and let's try again and make sure it downloads all three files that should exist in that directory.

**Comment by mdeldem** [comment]
Hello. I've the same problem as @AstroNeel98.
By setting `star.pim_dir` to the right directory, it's solve the problem.

**Comment by AstroNeel98** [comment]
Hello,

I have tried setting the` star.pm_dr` to the right directory in the code.  The file does exists in the said path. 

the pointing model has been set to 

`star.pm_dir = r'C:\Users\NEEL VADODARIA.eleanor\mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0001-4-1_tess_v2_pm.txt'
`
 After the run I am facing the same error as before. Then I verified the last row of the ASCII file that has the pointing model in it.

`0.9999596359856762 6.008149157113267e-05 4.0991388248558577e-19 8.714018857627337e-05 0.9999868047607952 -2.1849051656734444e-19 -1.0414253725236766 -1.036551762939438 1.000000000000002
`
They are same as that told by you in one of the previous replies.  Additionally I have tried by deleting all the files in the directory and trying again. All 3 files were downloaded by the code again, as expected. The problem still persists.

I am attaching the code and Program log once again for your reference. 
[Modified Path run.txt](https://github.com/afeinstein20/eleanor/files/4565732/Modified.Path.run.txt)
[Modified Path Run Log.txt](https://github.com/afeinstein20/eleanor/files/4565733/Modified.Path.Run.Log.txt)

**Comment by mdeldem** [comment]
@AstroNeel98 : You should set the `**directory** into `star.pm_dir` not the file.

`star.pm_dir = "C:\\Users\\Marc\\.eleanor\\mastDownload\\HLSP\\hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc"

**Comment by benmontet** [comment]
@mdeldem It looks like you are using a Windows machine as well? If so what was `star.pm_dir` originally set as, before you reset it? We can probably figure out a hack to sort this on Windows machines with that information.

**Comment by AstroNeel98** [comment]
I have tried once again and rectified the error of setting the file into `star.pm_dir`. However I am not seeing any change in the output. It is showing the same plots as I mentioned earlier. @mdeldem can you share more details about your setup or the logs / implementation of the basics light-curve generation on your setup ?

**Comment by AstroNeel98** [comment]
I was able to reproduce the curve given in the example by setting up `star.pm_dir` to `r'C:\Users\NEEL VADODARIA.eleanor\mastDownload\HLSP` . However this did not work if I set it up to
` star.pm_dir = r"C:\Users\NEEL VADODARIA\.eleanor\mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc"`

Another work around was to copy paste the downloaded Mast files to the folder where star.pm_dr is originally pointing to, in my case` C:\Users\NEEL VADODARIA\.eleanor`

Also, just in case anyone is new to python like me, \U has a special meaning and should be avoided while specifying the path. either append r to the path or use \\ .

**Comment by AstroNeel98** [comment]
Thank you @benmontet for the prompt replies and help. You are a savior.

**Comment by mdeldem** [comment]
@benmontet : Yes I'm using Windows 7 OS. `star.pm_dir` was pointing to `C:\Users\Marc\.eleanor` so I need to change it.

First I clean all the caches (`C:\Users\Marc\.eleanor and C:\Users\Marc\Documents\GitHub\eleanor\docs\getting_started`).
The first call to `star = eleanor.Source(tic=38846515, sector=1)` raises an error:
```
Downloading URL https://mast.stsci.edu/tesscut/api/v0.1/astrocut?ra=68.95970833333332&dec=-64.02703611111112&y=31&x=31&units=px&sector=1 to .\tesscut_20200503111947.zip ... [Done]
Inflating...
This is the first light curve you have made for this sector. Getting eleanor metadata products for Sector  1...
This will only take a minute, and only needs to be done once. Any other light curves you make in this sector will be faster.
Target Acquired
Cadences Calculated
Quality Flags Assured

---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-3-7a6a7e628cbc> in <module>
----> 1 star = eleanor.Source(tic=38846515, sector=1)
      2 
      3 print('Found TIC {0} (Gaia {1}), with TESS magnitude {2}, RA {3}, and Dec {4}'
      4      .format(star.tic, star.gaia, star.tess_mag, star.coords[0], star.coords[1]))

C:\ProgramData\Anaconda3\lib\site-packages\eleanor\source.py in __init__(self, tic, gaia, coords, name, fn, sector, fn_dir, tc, local, post_dir, pm_dir, metadata_path)
    244 
    245             if not os.path.isdir(self.metadata_path + '/metadata/s{:04d}'.format(self.sector)):
--> 246                 Update(sector=self.sector)
    247 
    248             if tc == False:

C:\ProgramData\Anaconda3\lib\site-packages\eleanor\update.py in __init__(self, sector)
    124             self.get_quality()
    125             print('Quality Flags Assured')
--> 126             self.get_cbvs()
    127             print('CBVs Made')
    128             print('Success! Sector {:2d} now available.'.format(self.sector))

C:\ProgramData\Anaconda3\lib\site-packages\eleanor\update.py in get_cbvs(self)
    179         files = [i for i in files if i.endswith('.fits')]
    180         for c in range(len(files)):
--> 181             os.remove(files[c])
    182 
    183 

PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'tess2018206045859-s0001-4-4-0120-s_cbv.fits'
```
I need to execute twice the `star = eleanor.Source(tic=38846515, sector=1)` command.
After this, `star.pm_dir` is pointing to `C:\Users\Marc\.eleanor`. 
I modify the directory with following command:
```
star.pm_dir = "C:\\Users\\Marc\\.eleanor\\mastDownload\\HLSP\\hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc"
```
Then, the remaining code is correctly running.

**Comment by benmontet** [comment]
Okay, thanks for posting this. My knowledge of windows is pretty limited but I will look into why this might be happening, the info you've given is useful.
