### ISSUE TITLE
No attribute version

### ISSUE THREAD

**Issue by idaira13** [afeinstein20/eleanor#182]
Hello, 

I have a recurrent issue, I've starting with eleanor to obtain curve lights, but when I use the class TargetData an attribute error come to my terminal:  
**_"module 'eleanor' has no attribute '__version__'"_**

and I don't know how to fix it, if anyone can help me I'd appreciate it. 

Thank u so mucho!

**Comment by benmontet** [comment]
Oh, this is a new one for me! Let's see...

1) Does the call to eleanor.Source() work fine? After you run that but before you call eleanor.TargetData(), can you print e.g. star.tic, star.coords, star.sector (assuming you assigned the eleanor.Source() object to the variable `star`) and does it look sensible?

2) If you print `eleanor.__path__`, does that path seem sensible? 

3) Did you install through pypi (pip) or github directly?

4) Do you have any local files in your directory (or in directories in your path) that are called eleanor.py? If so, you should move those.

That's probably a good place to start finding clues to what might be going wrong.

**Comment by idaira13** [comment]
Hello, 

first, I installed it with github but this morning I tried with pip and it works!. 

Thank u so much!!
