### ISSUE TITLE
Could you please add an interface to set the eleanorpath?

### ISSUE THREAD

**Issue by Flawintheory** [afeinstein20/eleanor#187]
For my server, the space of /home is limited, but we have a larger volume disk mounted on other directory. Do you have a easy way to change the default eleanorpath to another path? Or please implement it, thanks.

**Comment by ethankruse** [comment]
FWIW, the easy answer to this is just make `.eleanor` a symlink to the directory on the other disks. Copy all your stuff wherever you want, then make a symlink to there.
```
mv ~/.eleanor /path/to/bigger/disk
ln -s /path/to/bigger/disk ~/.eleanor
```

All the data storage will end up on the large disk, and every time eleanor tries to do anything, it'll use the .eleanor symlink to bounce into the correct location.

**Comment by Flawintheory** [comment]
Thanks for your simple method.

**Comment by benmontet** [comment]
That's a nice solution, thanks @ethankruse!
