### ISSUE TITLE
aperture_contour bugged?

### ISSUE THREAD

**Issue by ethankruse** [afeinstein20/eleanor#196]
I'm pretty sure you're misrepresenting the aperture in your visualization suite; you've got the aperture flipped about the y-axis from the image you're showing the aperture on.

https://github.com/afeinstein20/eleanor/blob/3ec238d4018cc1ff0d68cf5ffc2b3c74f604abd5/eleanor/visualize.py#L78-L113

Pretty simple test: just in front of line 100 where you imshow the pixels, add this line:
```
self.obj.tpf[0][aperture > 0] += 50000
```
That should add 50,000 counts only to pixels within your aperture. It should then be pretty obvious that your aperture lines match.

Here's an example of what I get out instead:
<img width="434" alt="Screen Shot 2020-09-21 at 7 50 45 PM" src="https://user-images.githubusercontent.com/6944089/93832434-bfda8900-fc43-11ea-9824-f7949518c6a6.png">

I also put in even more obvious custom apertures:
```
testap = np.zeros((vis.obj.aperture.shape))
testap[2,3] = 1
testap[9,7] = 1
vis.aperture_contour(aperture=testap)
```
which produced this
<img width="442" alt="Screen Shot 2020-09-21 at 9 43 52 PM" src="https://user-images.githubusercontent.com/6944089/93837301-8c9ff600-fc53-11ea-9cc3-df6920b83c55.png">

imshow's stupid origin choice makes these things messy. Whenever I mix any matplotlib stuff with imshow I always have to do a bunch of obviously non-symmetric tests to make sure I'm accounting for the origins correctly.

The solution here is to just remove the [::-1] from the `contour(Z[::-1]...)` call.

Finally, the `plt.contour(Z, [0.5], ...)` draws contours only around pixels where the aperture is greater than 0.5. If I'm not mistaken, you allow apertures with partial weights, correct? So might you want to lower that so that any pixels that contribute to the aperture in any way get highlighted?

Anyway, I discovered this when trying to test a pull request I was about to put in introducing a color_by_aperture function to the pixel_by_pixel plots. Let me know if this bug is indeed there, and if my fix + new feature are both ok.

**Comment by afeinstein20** [comment]
Hey Ethan thanks for catching this! Your pull request looked good, so I went ahead and merged it :) also coloring the subplot frame the same as the aperture is so cool!
