### ISSUE TITLE
Cannot use Eleanor as git submodule

### ISSUE THREAD

**Issue by martindevora** [afeinstein20/eleanor#211]
Hi,
I'm trying to use Eleanor as a submodule of one project whose name is 'myproject'. That is fine. The thing is that in order to use Eleanor I have to import it as:

`import myproject.eleanor`

That fails, because it implicitly tries to import targetdata, which also tries to import eleanor as it is. What I see is that targetdata only uses Eleanor to get its version. I'd suggest that the `import eleanor` line could be called into the methods that are needing it instead of doing it at the beginning of the file. Am I explaining it well? What do you think about it?

Kind regards.
Martín.

**Comment by benmontet** [comment]
Hi Martín,

I guess I don't fully understand your goals. What do you see as the benefit to structuring the package in a way to use it as a submodule of another project rather than just calling it? More plaining, why is it preferable in your case to then `import myproject.eleanor` rather than choosing to `import eleanor` at the top of your project, like you might `import numpy` or something similar?

Thanks!

**Comment by martindevora** [comment]
Hello,
thanks for answering. 

Because I need to use Python 3.8 and therefore I need to forget about the tensorflow dependency as mentioned in https://github.com/afeinstein20/eleanor/issues/188. To overcome that, I wanted to include Eleanor as a submodule so that pip doesn't force to install tensorflow, but I run into the issue that I explained in the OP. Therefore, I had to fork the Eleanor repo and make slight changes to make it work as a submodule.

Kind Regards.

**Comment by benmontet** [comment]
I see. I'm glad you found a way that works!

We are working through removing the tensorflow dependency, and are closer to making that a reality. As an additional workaround if you must use 3.8, you could download the code from github, remove the tensorflow installation instructions from setup.py, and then (as long as you don't want to do any psf modeling, which is the only place it's used) it should install and run as normal, and you should be able to do anything else you'd like with it.

Given you've found a workaround that works for you, and the removal of tensorflow isn't that far off, I'm happy with not making any specific changes to the code base. If you would like to contribute your modifications as a pull request, you are welcome to do that and we'll add them in.

**Comment by martindevora** [comment]
Thanks for your answer. I have created a pull request. Regards.

**Comment by benmontet** [comment]
Fantastic, thanks! I have merged your changes in, they look fine to me, so they are available now through the github version and will propagate through into the pip version the next time we do a version update. 

I'm therefore going to close this issue, if issues related to this pop up do feel free to re-open.
