### ISSUE TITLE
update.py does not create ~/.eleanor/metadata

### ISSUE THREAD

**Issue by altuson** [afeinstein20/eleanor#221]
Tried to run eleanor.Update(sector=31) but got an error that it couldn't create sector folder. Looked at source code and noticed that it never creates the metadata folder to put the sector folder in. I manually created this folder and the code now runs ok.

**Comment by benmontet** [comment]
Hey, yes that checks out. We create metadata in `eleanor.Source()` if it does not exist, which originally was the default behaviour for everyone, you used to download all the metadata in the repository which also necessitated a version update every month. And I guess the first thing people normally do is run the demo to make sure their code works properly, which will create it, but if you jump right in to s0031 you'll never hit that step and create it.

I added a line in update that checks for this folder and creates it if it doesn't exist, so should work automagically moving forward. 

Thanks!
