### ISSUE TITLE
'primary' and 'secondary' keywords for eleanor.multi_sectors

### ISSUE THREAD

**Issue by rachelbf** [afeinstein20/eleanor#223]
I was wondering if 'primary' and 'secondary' could be added to eleanor.multi_sectors in order to only get the light curves for whichever mission you want? I have already tried [1,2,3,4,5,6,7,8,9,10,....., 24, 25, 26] to get only the primary mission light curves but that didn't work.
Given that the two have different FFI cadences, it makes it but hard to run further analyses on the stitched light curves.

**Comment by benmontet** [comment]
I would advocate for using as much data as possible and not limiting yourself to just primary vs extended mission data. The physical processes you're investigating don't depend on the timescale at which they're observed!

You're correct that passing in a list to `multi_sectors` assumes that users are passing through a list of specific sectors *with data* that they want, with our assumption that if they don't know what sectors the star is observed in they probably want all the data. If you geniunely only want part of the data, you can 

- change the maxsector.py file to limit yourself to sectors < maxsector
- use a tool like tess-point to identify what sectors your star is observed in, then pass the list it returns back into `eleanor.multi_sectors()`
- get all the TPFs for all sectors, and then limit your analysis further downstream to only the sectors you care about.

If all three of those options are untenable for your research goals let me know and we can talk through other options.
