### ISSUE TITLE
Issue extracting light curve from sector 27

### ISSUE THREAD

**Issue by rachelbf** [afeinstein20/eleanor#224]
I am using eleanor (2.0.1) to extract the lightcurve of a particular star that was observed in sectors 12, 13 and 27. It was able to extract the lightcurves for 12 and 13 but shows this error for sector 27:
![Screen Shot 2021-02-03 at 15 02 04](https://user-images.githubusercontent.com/48811452/106815499-31ced000-6631-11eb-9ed5-c9cfaf73ce37.png)

**Comment by benmontet** [comment]
This seems to be the same issue as #214 and #220. The github version has fixed that issue so if you use that version (or at least copy-pate that `targetdata.py` into your `eleanor.__path__`, overwriting the old one) you won't run into this bug.

It will get percolated through into the next pypi version update, when that occurs.

I'm thus going to close this as a duplicate, if you feel this is actually a different issue than either of those then feel free to re-open.
