### ISSUE TITLE
Update SFFCorrector lightkurve import in targetdata.py

### ISSUE THREAD

**Issue by rachelbf** [afeinstein20/eleanor#226]
**Issue:** 
![Screen Shot 2021-02-23 at 13 12 51](https://user-images.githubusercontent.com/48811452/108905286-c39c7e00-75dc-11eb-9eed-98045acde940.png)

**Fix:** 
```
from lightkurve import lightcurve
from lightkurve.correctors import SFFCorrector
```

**Source:** 
Unexpected error while importing SFFCorrector from lightkurve (via eleanor) after latest update #975:
https://github.com/lightkurve/lightkurve/issues/975

**Comment by afeinstein20** [comment]
Hi Rachel, 

`lightkurve>=2.0.0` has some major (and super awesome!) updates, many of which have not been incorporated into `eleanor` yet. This is one example of such. I have pushed a quick fix to the `eleanor/dev-lightkurve2.0` branch, which can be found [here](https://github.com/afeinstein20/eleanor/tree/dev-lightkurve2.0). Once we're sure all of `eleanor` is fully compatible with `lightkurve>=2.0.0`, we'll do a version update.

Hope that helps,
Adina

**Comment by afeinstein20** [comment]
(woops, didn't mean to close that until you confirm that fix works -- sorry!)

**Comment by rachelbf** [comment]
No worries!
I just edited my copy of targetdata.py as in my original post (which seems be the same as your edit), so far it seems to work.
