### ISSUE TITLE
Source() failed in lastest main due to indentation error

### ISSUE THREAD

**Issue by orionlee** [afeinstein20/eleanor#232]
With the latest `main`, I got an indentation error when trying to create a Source.

It looks like the most recent commit 01f8620d9bd17b42f0818ca1c0de1b589001fbdd changed the indentation of line 156 (the `try`).

https://github.com/afeinstein20/eleanor/blob/01f8620d9bd17b42f0818ca1c0de1b589001fbdd/eleanor/source.py#L154-L159

The change in indentation in line 151 probably had the same problem, but I haven't hit it yet.

**Comment by afeinstein20** [comment]
Hi @orionlee ! Thanks for pointing this out. I believe the problem should be fixed. If you're still producing this error, please reopen this issue.
