### ISSUE TITLE
Inconsistent orientation in visualization plots

### ISSUE THREAD

**Issue by orionlee** [afeinstein20/eleanor#233]
The orientation in visualization plots are inconsistent. It'd be better if they are consistent.
- `aperture_contour()` and `pixel_by_pixel()` plot row 0 from the top
- `plot_gaia_overlay()` plots row 0 from the bottom

Example:

`aperture_contour()`:
![image](https://user-images.githubusercontent.com/250644/129839246-566dadb4-7dfb-45d2-b12e-fcd3b768a829.png)

`plot_gaia_overlay()`
![image](https://user-images.githubusercontent.com/250644/129839264-5ea0ba8d-4bfb-4208-9852-363cac97c034.png)

**Comment by afeinstein20** [comment]
Hi @orionlee ! The orientations have been fixed so that they are all consistent. Thanks for bringing this issue to our attention!

**Comment by orionlee** [comment]
Not completed fixed yet. 
For `pixel_by_pixel()`, the fix in commit 0d36441 fixed the small plot at the left, but not the main plot at the right.
