### ISSUE TITLE
New point release 2.0.4

### ISSUE THREAD

**Issue by ethankruse** [afeinstein20/eleanor#239]
Hey,

Can you release a new version, 2.0.4 with what is currently out?

Right now in 2.0.3 you can't get any ecliptic plane data because `eleanor.Update` is failing because it's looking for targets in the CVZ. It seems like Ben fixed this in a PR in September, but to get that working you have to download from source instead of using pip upgrades. Our group has some novice python users where downloading and installing from source is a bit of a challenge.

**Comment by afeinstein20** [comment]
done!

**Comment by ethankruse** [comment]
Wow that was fast! Thanks! Might be worth a tweet to notify people to upgrade to get access to the ecliptic.
