### ISSUE TITLE
Enhancement: Add keyword to enable FAP values in pixel-by-pixel periodogram

### ISSUE THREAD

**Issue by shbhuk** [afeinstein20/eleanor#240]
Hi,
Suggestion for a new keyword in the `vis.pixel_by_pixel()`, perhaps called FAP which can be `None` by default, but if the `data_type='periodogram'`, and `FAP is not None`, then it can plot horizontal dashed lines corresponding to the False Alarm Probabilities for the LS periodogram?

I plan to include this in a forked version of the `master` repo for a project. If you think it's useful, I can issue a pull request to merge it with a `dev` branch. 

Shubham

**Comment by afeinstein20** [comment]
Sorry for the slow response here! I'm going to look at your PR now
