### ISSUE TITLE
Problem with multi_sector and tc = True

### ISSUE THREAD

**Issue by doccosmos** [afeinstein20/eleanor#251]
Using eleanor v2.0.4 and Python 3.7.12:

ra, dec = 1.636263967, 62.16889954
coords = SkyCoord(ra = ra, dec = dec, unit = (u.deg, u.deg))
star = eleanor.multi_sectors(sectors = 'all', coords = coords, tc = True)

gives:

Found star in Sector(s) 17 18 24
Traceback (most recent call last):
  File "testtess.py", line 12, in <module>
    star = eleanor.multi_sectors(sectors = 'all', coords = coords, tc = True)
  File "/opt/anaconda3/envs/eleanor/lib/python3.7/site-packages/eleanor/source.py", line 76, in multi_sectors
    metadata_path=metadata_path, tesscut_size=tesscut_size)
  File "/opt/anaconda3/envs/eleanor/lib/python3.7/site-packages/eleanor/source.py", line 267, in __init__
    self.locate_with_tesscut() # sets sector, camera, chip, postcard,
  File "/opt/anaconda3/envs/eleanor/lib/python3.7/site-packages/eleanor/source.py", line 439, in locate_with_tesscut
    manifest = Tesscut.download_cutouts(coords, self.tesscut_size, sector=self.sector, path=download_dir)
TypeError: download_cutouts() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given

**Comment by afeinstein20** [comment]
Hi @doccosmos ! Thanks for raising this. It's an issue with astropy actually. The best fix would be to clone and install the most recent GitHub version of `eleanor` with the following:

```
 git clone https://github.com/afeinstein20/eleanor
cd eleanor
python setup.py install
```

Let me know if that doesn't fix the problem!

**Comment by doccosmos** [comment]
Hi,

Yes, that solves the problem.

Thanks,

Matthew

**Comment by afeinstein20** [comment]
Great! I'm going to go ahead and close the issue then. Feel free to reopen it if you run into similar problems later
