### ISSUE TITLE
Couldn't find pointing model

### ISSUE THREAD

**Issue by UrsaMajoris** [afeinstein20/eleanor#252]
Hi,

I recently installed Eleanor (windows) using conda environment. At first, I got tf error which I bypassed by installing an earlier version to meet the requirement of tf<20 . After that, I was able to install it without any errors. Now when I run the following query:

star = eleanor.Source(tic=279906586, sector=6)

print('Found TIC {0} (Gaia {1}), with TESS magnitude {2}, RA {3}, and Dec {4}'
     .format(star.tic, star.gaia, star.tess_mag, star.coords[0], star.coords[1]))

I get this error:

ost recent sector available =  50
This sector isn't available yet.
C:\Users\sayab\anaconda3\lib\site-packages\eleanor\ffi.py:40: UserWarning: couldn't find pointing model
  warnings.warn("couldn't find pointing model")
Downloading URL https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HLSP/eleanor/postcards/s0006/1-2/hlsp_eleanor_tess_ffi_postcard-s0006-1-2-cal-1392-0970_tess_v2_bkg.fits to ./mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0006-1-2-cal-1392-0970_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0006-1-2-cal-1392-0970_tess_v2_bkg.fits ...
|===========================================|  61M/ 61M (100.00%)         0s
WARNING: Found cached file ./mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0006-1-2-cal-1392-0970_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0006-1-2-cal-1392-0970_tess_v2_bkg.fits with size 0 that is different from expected size 61162560 [astroquery.query]
INFO: Found cached file ./mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0006-1-2-cal-1392-0970_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0006-1-2-cal-1392-0970_tess_v2_pc.fits with expected size 122411520. [astroquery.query]
INFO: Found cached file ./mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0006-1-2-cal-1392-0970_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0006-1-2_tess_v2_pm.txt with expected size 185371. [astroquery.query]
Found TIC 279906586 (Gaia 3107260649407047936), with TESS magnitude 10.0794, RA 100.588921174734, and Dec -1.19656022130841
C:\Users\sayab\anaconda3\lib\site-packages\eleanor\ffi.py:40: UserWarning: couldn't find pointing model

How can I remove it?

**Comment by UrsaMajoris** [comment]
consequently, I am not able to run eleanor.TargetData

**Comment by afeinstein20** [comment]
Hi @UrsaMajoris ! Thanks for bringing this to our attention. 2 fixes come to mind:

1. What version of `eleanor` are you running? If you have `v<2.0.5` I recommend upgrading to the latest version. This can be done via the following:

```
git clone https://github.com/afeinstein20/eleanor
cd eleanor
python setup.py install
```

2. And you may have an incomplete `metadata` directory. You can do this by going to `$HOME/.eleanor/metadata/s0006` and deleting all files in that directory.

Please let me know if either of these work/don't work!

**Comment by UrsaMajoris** [comment]
Thank you. I checked the metadata directory and it was empty (no s0006 sub-directory in it either), which might be because I did not update the sector before calling eleanor.Source I guess. However, updating to the latest version removes the problem.
I am working on a target which is currently in southern hemisphere. It was observed in sector 6 and sector 33. Is sector 33 available?

**Comment by benmontet** [comment]
Great, glad it's sorted, I'll go ahead and close this issue, feel free to re-open it if you're having further problems.

No, at this time postcards only exist for sectors 1-13; all future sectors use TessCut to create a postcard-like object. You can change the size of the region cutout in tesscut to get something very similar to a postcard, if you would like.
