### ISSUE TITLE
Astropy causing Eleanor to break

### ISSUE THREAD

**Issue by rachelbf** [afeinstein20/eleanor#253]
I have been running into this astropy issue via Eleanor for several targets (e.g. TIC 99381773, s48) now and none of the solutions have worked for me: https://github.com/astropy/astropy/issues/13007

It prevents me from downloading any FFI data. I have Python 3.7, Eleanor 2.0.4, astropy 4.3.1. Is there an astropy version that I can use instead?

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/core.py in _convert_vals(self, cols)
   1056                 try:
-> 1057                     converter_func, converter_type = col.converters[0]
   1058                     if not issubclass(converter_type, col.type):

IndexError: list index out of range

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-94c62d7adc0a> in <module>
      7     tic = TIC(ID, Verbose=False, save_on_disk=True)
      8     try:
----> 9         tic.extract_lightcurve(lctype = 'psf',save_on_disk=True, NormalizeSegments=True, Verbose=False, Overwrite = True)
     10         tics.append(tic)
     11         found.append(tic.tic)

/Volumes/GoogleDrive/My Drive/Pterry10/Python Routines/pterry10/tic.py in extract_lightcurve(self, lctype, do_psf, do_pca, store_all_lightcurves, save_on_disk, Overwrite, NormalizeSectors, NormalizeSegments, Verbose)
    511                 else:
    512 			lcs= self.lightcurve_from_eleanor(save_on_disk=save_on_disk,
--> 513 				do_psf = do_psf, do_pca = do_pca, Verbose=Verbose)
    514                 # Normalize all segments to median flux
    515 

/Volumes/GoogleDrive/My Drive/Pterry10/Python Routines/pterry10/tic.py in lightcurve_from_eleanor(self, do_psf, do_pca, crowded_field, store_all_lightcurves, save_on_disk, Verbose)
    157                 for star in stars:
    158                         print ('eleanor.TargetData sector {}'.format(star.sector))
--> 159                         data = eleanor.TargetData(star, do_psf = do_psf, do_pca = do_pca, regressors = 'corner')
    160                         for sector in self.sectors:
    161 			    s27_mask = [466265409, 1815932993, 234284556, 261560580, 391745863, 259928422, 176980970, 260474818, 370324024, 197963243,

~/opt/anaconda3/lib/python3.7/site-packages/eleanor/targetdata.py in __init__(self, source, height, width, save_postcard, do_pca, do_psf, bkg_size, aperture_mode, cal_cadences, try_load, regressors, language)
    188                 self.ffiindex = self.post_obj.ffiindex
    189                 self.flux_bkg = self.post_obj.bkg
--> 190                 self.get_time(source.coords)
    191 
    192                 if bkg_size is None:

~/opt/anaconda3/lib/python3.7/site-packages/eleanor/targetdata.py in get_time(self, coords)
    257         times = time.Time(t0+2457000, format='jd',
    258                    scale='utc', location=greenwich)
--> 259         ltt_bary = times.light_travel_time(SkyCoord(ra, dec)).value
    260 
    261         self.time = t0 + ltt_bary

~/opt/anaconda3/lib/python3.7/site-packages/astropy/time/core.py in light_travel_time(self, skycoord, kind, location, ephemeris)
   1756                 # first we need to convert to GCRS coordinates with the correct
   1757                 # obstime, since ICRS coordinates have no frame time
-> 1758                 gcrs_coo = itrs.transform_to(GCRS(obstime=self))
   1759                 # convert to barycentric (BCRS) coordinates, aligned with ICRS
   1760                 cpos = gcrs_coo.transform_to(ICRS()).cartesian.xyz

~/opt/anaconda3/lib/python3.7/site-packages/astropy/coordinates/baseframe.py in transform_to(self, new_frame)
   1230             msg = 'Cannot transform from {0} to {1}'
   1231             raise ConvertError(msg.format(self.__class__, new_frame.__class__))
-> 1232         return trans(self, new_frame)
   1233 
   1234     def is_transformable_to(self, new_frame):

~/opt/anaconda3/lib/python3.7/site-packages/astropy/coordinates/transformations.py in __call__(self, fromcoord, toframe)
   1420 
   1421             curr_toframe = t.tosys(**frattrs)
-> 1422             curr_coord = t(curr_coord, curr_toframe)
   1423 
   1424         # this is safe even in the case where self.transforms is empty, because

~/opt/anaconda3/lib/python3.7/site-packages/astropy/coordinates/transformations.py in __call__(self, fromcoord, toframe)
   1023             return reprwithoutdiff.realize_frame(reprwithdiff)
   1024         else:
-> 1025             return supcall(fromcoord, toframe)
   1026 
   1027 

~/opt/anaconda3/lib/python3.7/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py in itrs_to_cirs(itrs_coo, cirs_frame)
    211 def itrs_to_cirs(itrs_coo, cirs_frame):
    212     # compute the pmatrix, and then multiply by its transpose
--> 213     pmat = cirs_to_itrs_mat(itrs_coo.obstime)
    214     newrepr = itrs_coo.cartesian.transform(matrix_transpose(pmat))
    215     cirs = CIRS(newrepr, obstime=itrs_coo.obstime)

~/opt/anaconda3/lib/python3.7/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py in cirs_to_itrs_mat(time)
     50 def cirs_to_itrs_mat(time):
     51     # compute the polar motion p-matrix
---> 52     xp, yp = get_polar_motion(time)
     53     sp = erfa.sp00(*get_jd12(time, 'tt'))
     54     pmmat = erfa.pom00(xp, yp, sp)

~/opt/anaconda3/lib/python3.7/site-packages/astropy/coordinates/builtin_frames/utils.py in get_polar_motion(time)
     45     """
     46     # Get the polar motion from the IERS table
---> 47     iers_table = iers.earth_orientation_table.get()
     48     xp, yp, status = iers_table.pm_xy(time, return_status=True)
     49 

~/opt/anaconda3/lib/python3.7/site-packages/astropy/utils/state.py in get(cls)
     38         Get the current science state value.
     39         """
---> 40         return cls.validate(cls._value)
     41 
     42     @classmethod

~/opt/anaconda3/lib/python3.7/site-packages/astropy/utils/iers/iers.py in validate(cls, value)
    860     def validate(cls, value):
    861         if value is None:
--> 862             value = IERS_Auto.open()
    863         if not isinstance(value, IERS):
    864             raise ValueError("earth_orientation_table requires an IERS Table.")

~/opt/anaconda3/lib/python3.7/site-packages/astropy/utils/iers/iers.py in open(cls)
    692             return cls.iers_table
    693 
--> 694         cls.iers_table = cls.read(file=filename)
    695         cls.iers_table.meta['data_url'] = all_urls[0]
    696 

~/opt/anaconda3/lib/python3.7/site-packages/astropy/utils/iers/iers.py in read(cls, file, readme)
    545             readme = IERS_A_README
    546 
--> 547         iers_a = super().read(file, format='cds', readme=readme)
    548 
    549         # Combine the A and B data for UT1-UTC and PM columns

~/opt/anaconda3/lib/python3.7/site-packages/astropy/table/connect.py in __call__(self, *args, **kwargs)
     59         descriptions = kwargs.pop('descriptions', None)
     60 
---> 61         out = registry.read(cls, *args, **kwargs)
     62 
     63         # For some readers (e.g., ascii.ecsv), the returned `out` class is not

~/opt/anaconda3/lib/python3.7/site-packages/astropy/io/registry.py in read(cls, format, cache, *args, **kwargs)
    525 
    526         reader = get_reader(format, cls)
--> 527         data = reader(*args, **kwargs)
    528 
    529         if not isinstance(data, cls):

~/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/connect.py in io_read(format, filename, **kwargs)
     16         format = re.sub(r'^ascii\.', '', format)
     17         kwargs['format'] = format
---> 18     return read(filename, **kwargs)
     19 
     20 

~/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/ui.py in read(table, guess, **kwargs)
    367         else:
    368             reader = get_reader(**new_kwargs)
--> 369             dat = reader.read(table)
    370             _read_trace.append({'kwargs': copy.deepcopy(new_kwargs),
    371                                 'Reader': reader.__class__,

~/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/cds.py in read(self, table)
    336                     return table
    337         else:
--> 338             return super().read(table)

~/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/core.py in read(self, table)
   1374                                      self.include_names, self.exclude_names)
   1375 
-> 1376         table = self.outputter(self.header.cols, self.meta)
   1377         self.cols = self.header.cols
   1378 

~/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/core.py in __call__(self, cols, meta)
   1110         # Sets col.data to numpy array and col.type to io.ascii Type class (e.g.
   1111         # FloatType) for each col.
-> 1112         self._convert_vals(cols)
   1113 
   1114         t_cols = [numpy.ma.MaskedArray(x.data, mask=x.mask)

~/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/core.py in _convert_vals(self, cols)
   1073                     last_err = err
   1074                 except IndexError:
-> 1075                     raise ValueError(f'Column {col.name} failed to convert: {last_err}')
   1076 
   1077 

ValueError: Column year failed to convert: invalid literal for int() with base 10: '<!'`

**Comment by benmontet** [comment]
I am able to do things just fine with astropy 5.0.4 on my local machine. 

Reading through the traceback and the astropy bug report you linked it seems to be an ICRS issue so deleting your astropy cache at ~/.astropy/cache/download/url is probably a good start (and perhaps everything at ~/.astropy/cache if you've recently upgraded your astropy version)

Beyond that this isn't an eleanor issue, as you note it's an astropy issue, so there's not really anything that we can do with the eleanor codebase to solve this one. For that reason I'm going to close this issue, and I'd recommend reaching out to the astropy crew for advice if clearing out your cache doesn't solve your problem.
