### ISSUE TITLE
audit import statements

### ISSUE THREAD

**Issue by megbedell** [afeinstein20/eleanor#33]
There are quite a instances of importing packages inside a function. We should audit these and make sure it's really beneficial to do this. I would err on the side of putting all import statements at the top unless it's a function that's really rarely used and a package that takes a while to import. I noticed this issue most in `targetdata.py`.

**Comment by benmontet** [comment]
Audited and I think I'm happy with how they are arranged now. @afeinstein20 please verify you're happy and if so close issue!
