### ISSUE TITLE
"pointing_model_per_cadence" doesn't run

### ISSUE THREAD

**Issue by dfm** [afeinstein20/eleanor#50]
When I run `pointing_model_per_cadence` on `ffi`, it fails because of a few different bugs (some of which I will fix in an upcoming pull request) but others that are deeper than I'm willing to go. The place where it's stuck now is when it calls `tic_by_contamination`.

**Comment by benmontet** [comment]
What us the error you are getting? I don’t get why this is failing now
after not having any previous issues being created in other iterations

**Comment by benmontet** [comment]
@afeinstein20 can you test this on archipelago and see where it now breaks?

**Comment by afeinstein20** [comment]
![screen shot 2018-12-19 at 10 49 52 am](https://user-images.githubusercontent.com/5041100/50234695-dde2cd80-037b-11e9-9fe3-be363cddf9ca.png)

If this is the error you were getting, this is a problem with connecting to MAST, not anything in our scripts. It might take 2-3 times to get it to fully connect
