### ISSUE TITLE
CADENCENO flags

### ISSUE THREAD

**Issue by benmontet** [afeinstein20/eleanor#55]
Ethan Kruse has suggested a table of CADENCENOs to be included, in addition to the timestamps. This is something that will exist in the FFI data starting from sector 5, apparently. I am cool with us putting it in at that point but we should not spend too much time thinking about it now---it will be easier for us to understand their numbering convention and add this in at that future time when we reprocess sectors 1-4 at the end of the year. Putting it here so we do not forget!

**Comment by ethankruse** [comment]
FYI: indeed starting in sector 5 they added cadence numbers. It's in the first header as `header['ffiindex']` I believe. Worth adding that as an extra one-dimensional array (equivalent to `time`) in all of your data products starting in S5.

For bonus points, you could be proactive (or ask someone like me or Tom Barclay) to get the ffiindex of the first cadence in each sector and add them now for your S1-4 data products delivered to MAST as well to be consistent in your file format for all sectors.

Looks like they're being consistent with Kepler and increasing the ffiindex every 30 minutes regardless of whether they're taking data or not, so it's easy to interpolate/extrapolate to get "missing" cadence numbers for previous sectors.

**Comment by benmontet** [comment]
There is now a directory called 'metadata' in here that has the ffiindex values for the first six sectors. This will be folded into the postcards (and thus the TPFs) as delivered to MAST, but can be used now by the ambitious (they're just lists of integers of the same length as data.time). Next step, sorting processing and delivery.
