### ISSUE TITLE
Make guide for multiple camera/chip combinations

### ISSUE THREAD

**Issue by dfm** [afeinstein20/eleanor#56]
Running `make_guide` on one camera/chip works, but running on a full sector does not because there are some keys that depend on the camera or chip (for example `3-2` has the key `TMOFST32` and `4-1` has the key `TMOFST41`). What do y'all want to do about that?

**Comment by benmontet** [comment]
Dang, that's a strange convention!

It looks to me that that's the only key that's different in each camera/chip. It's a time offset, first number is the camera and second the chip. I propose we just carry it through, defining a variable as TMOFST and setting it to the value for TMOFST{camera}{chip}. (I'm also not opposed to just tossing it, if you both felt strongly in that direction) @afeinstein20 that plan cool with you?

**Comment by benmontet** [comment]
Let's just make it TMOFST and run with that!

**Comment by afeinstein20** [comment]
I'm cool with that! It's dumb... But I'm good with this work around
