### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by benmontet** [afeinstein20/eleanor#57]
@nksaunders can I task you with updating the tests so it passes? I believe it should at this point, everything (except PCA for now, but there's no test for that?) should work for sector 1. I removed the multi-sector test, and I think the others should work but we're getting a failure right now!

**Comment by nksaunders** [comment]
Yes, I'll take a look!

**Comment by benmontet** [comment]
Tests passed, great, thanks!

Docs failed. Do you have expertise in nbconvert? We're getting an issue with a decorator:
```
Exception occurred:
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```
But it works fine on my machine to make them, so it's some version issue somewhere I think! (Also our docs ran fine previously, right?)

**Comment by nksaunders** [comment]
I'm not as familiar with building docs, so this error doesn't make much sense to me. I think @megbedell did most of the setup for documentation, any idea what's going on here?

**Comment by megbedell** [comment]
No idea, looks like maybe the version of something being imported on travis is wrong? @rodluger set up the travis bits.

**Comment by benmontet** [comment]
nbconvert relies on a package called tornado. Over the weekend tornado upgraded from 5.1.1 to 6.0, which broke the way nbconvert uses it. We're now explicitly calling tornado 5.1.1 with travis and this solves everything, we're back to passing.
