### ISSUE TITLE
Can't install on Python 3.7 due to tensorflow dependency

### ISSUE THREAD

**Issue by ethankruse** [afeinstein20/eleanor#61]
Don't know if this is a known issue or not, but I couldn't find anything in your docs or mentions here: you're currently incompatible with Python 3.7 because tensorflow doesn't have a 3.7 package yet. I tried installing via pip and it failed when it tried to install tensorflow as a dependency. (See [here](https://github.com/tensorflow/tensorflow/issues/20517).)

It's not your fault, it's pretty absurd that 3.7 has been out for 6 months and they don't have a package running on the latest Python version (that things like anaconda and miniconda are installing as the default), but here we are.

So I guess on your end, either explicitly put Python  3.0 <= version < 3.7 as your python version requirements (or whatever the min version you support is) and make some sort of note on your install page and/or elsewhere in the docs.

**Comment by benmontet** [comment]
Ah shoot, this was not known on our end! Removing upgrade to 3.7 from my to-do list. That is silly!

The upshot is that the only thing that requires tensorflow is psf modeling, and I believe we've coded it in a way to where tensorflow only gets imported when psf modeling is called, so if you were to install it with the --no-dependencies, it should work as long as you don't set do_psf == True when you make a light curve. I think.

My gut instinct is to remove tensorflow from the required packages (or have different requirements for different python versions?), and then add a warning in the code if someone tries to do psf modeling without tensorflow, and then include an explanation in the docs. My hope is that this would be a temporary problem though.

I'm curious to hear your thoughts on the "right" approach, @rodluger @nksaunders @mirca @dfm

**Comment by rluquer** [comment]
You can overcome the problem installing tensorflow for Python3.7 using: 
`pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl`
You can install eleanor afterwards using pip and there will be no problem.

**Comment by ethankruse** [comment]
As an update, tensorflow 1.13.0 supports Python 3.7. It's currently just in a release candidate, but pip will install that by default when you try to install eleanor. It seems like everything is working, pip installs eleanor and all dependencies, and doing PSF fitting seems to be fine and successfully runs some tensorflow stuff on 3.7 now.

I think this can safely be closed with no further work on your end.
