### ISSUE TITLE
Documentation does not include install instructions

### ISSUE THREAD

**Issue by ceb8** [afeinstein20/eleanor#64]
The eleanor docs page here: http://adina.feinste.in/eleanor/ does not seem to include instructions on installing eleanor.

**Comment by benmontet** [comment]
I don't know how that happened, I must have accidentally deleted it at some point!

The installation instructions were/are on the main github readme visible at https://github.com/afeinstein20/eleanor, and are now in the docs as well. Thanks for pointing this out!
