### ISSUE TITLE
Error Downloading Target in CVZ using Gaia ID

### ISSUE THREAD

**Issue by elliesch** [afeinstein20/eleanor#71]
I'm trying to query a Gaia star. `eleanor` locates the TIC using `eleanor.source`, but when I try to access the lightcurve using `eleanor.TargetData(star,...)`, the following error is thrown:

``` python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/astropy/io/ascii/core.py in _convert_vals(self, cols)
    952                 try:
--> 953                     converter_func, converter_type = col.converters[0]
    954                     if not issubclass(converter_type, col.type):

IndexError: list index out of range

During handling of the above exception, another exception occurred:

...

~/anaconda3/lib/python3.6/site-packages/astropy/io/ascii/core.py in _convert_vals(self, cols)
    967                     last_err = err
    968                 except IndexError:
--> 969                     raise ValueError('Column {} failed to convert: {}'.format(col.name, last_err))
    970 
    971 

ValueError: Column year failed to convert: invalid literal for int() with base 10: '<h'
```

I have astropy 3.1.2. Maybe this is due to differing astropy versions?

**Comment by benmontet** [comment]
I have astropy 3.0.3 on my machine. @afeinstein20 what about you?

This could very well be an astropy versioning issue, but first let's make sure that your call runs locally for us. @elliesch can you please send us exactly how you're calling everything to get this error? And is this the first star you've tried, or do other stars work well and this one creates an error?

**Comment by elliesch** [comment]
I just created an environment with astropy 3.0.3 and I triggered the same error. I've been following the quick start tutorial, and these are the commands that I've been trying.

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image
import eleanor

star = eleanor.Source(gaia=source_id[0], sector=1)

print('Found TIC {0} (Gaia {1}), with TESS magnitude {2}, RA {3}, and Dec {4}'
     .format(star.tic, star.gaia, star.tess_mag, star.coords[0], star.coords[1]))

data = eleanor.TargetData(star, height=15, width=15, bkg_size=31, do_psf=True, do_pca=True)
```

The error is thrown on the last line. So far I've tried on a few stars, but I have received the same error on all of them. Thanks for looking into this!

**Comment by benmontet** [comment]
Can you please either post or email the list of stars you’re trying, for
conpleteness? I want to make sure we’re testing the exact same thing.

The coords it prints are what you expect, right?

**Comment by elliesch** [comment]
Sure! Here are three examples. I've listed the Gaia source_id followed by the print output from the Quickstart Tutorial. The RA and Dec are exactly what I expect, so the crossmatch is working beautifully. (Printed at the end of the line along with Gaia G)

Stars in the CVZ that aren't working:

4648821478203114112
```Found TIC 407662707 (Gaia 4648821478203114112), with TESS magnitude 16.389, RA 83.2001037550371, and Dec -74.18469907555149. Gaia G: 17.88668 RA: 83.2001037550371 Dec:-74.18469907555149```

4660161188336775296
```Found TIC 425084883 (Gaia 4660161188336775296), with TESS magnitude 13.689, RA 82.8588472748885, and Dec -67.02329765674841. Gaia G: 14.213067 RA: 82.8588472748885 Dec: -67.02329765674841```

5264273386722406528
```Found TIC 300601545 (Gaia 5264273386722406528), with TESS magnitude 14.471, RA 113.20921506628898, and Dec -71.2856947691204. Gaia G: 15.234189 RA: 113.20921506628898 Dec: -71.2856947691204```

**Comment by elliesch** [comment]
What versions of all the dependencies do you have in your environment? I can make a similar environment locally and see if that eliminates the errors.

**Comment by benmontet** [comment]
Confirming that this example works on my machine, so I agree that it is
very likely some dependency versioning issue.

I am using
python 3.5.2
numpy 1.14.4
astropy 3.0.3
mpl 2.2.3
fitsio 0.9.11

I think it must be with one of those (and probably not matplotlib). The
error is when astropy is trying to be used to read in some table data, so I
wouldn't be surprised if it's fitsio, but I really don't know! To my
knowledge you're the first one to run into this issue so we'll learn
together.

**Comment by elliesch** [comment]
Thank you! It's working in an environment now! I think it might be a bug with the latest `astropy` update, because someone else I spoke with triggers the same error when importing the latest version of `astroquery` before `eleanor`. I'll reach out to them to find out.
