### ISSUE TITLE
Stars not on the detector being found

### ISSUE THREAD

**Issue by benmontet** [afeinstein20/eleanor#72]
David noticed that when he gives the coords (152.86113, -38.63042) this does return a position on the CCD and then fails in doing a good job correcting the WCS (which makes sense, halfway across the sky). Why does this one get found in the guide? I don't know but we should figure it out!

**Comment by afeinstein20** [comment]
Never fear! I found the star! [ WCS(header).all_world2pix(ra, dec, 1, **quiet=True**), the quiet part is necessary. It silences the NoConvergence exception and the translated coordinates are still valid. ]
