### ISSUE TITLE
Issue with downloading postcard

### ISSUE THREAD

**Issue by rachelbf** [afeinstein20/eleanor#73]
Kernel keeps crashing when trying to download the postcard (using Jupyter) as can be seen in the screenshot. 
When I use the terminal instead, python just quits unexpectedly. Not sure why. I am using Python 3.6.
![Screen Shot 2019-03-21 at 4 28 32 PM](https://user-images.githubusercontent.com/48811452/54791284-734d6200-4bf6-11e9-83c1-745cba3a92b8.png)
![Screen Shot 2019-03-21 at 4 28 41 PM](https://user-images.githubusercontent.com/48811452/54791285-734d6200-4bf6-11e9-8127-bed77e04b22f.png)

**Comment by benmontet** [comment]
Which cell is it crashing when you try to execute? Is it the .TargetData call?

Based off the warning, it's certainly having issues trying to create the directory where it will store the postcards. I don't know that it's related, but it's the first obvious thing that comes to mind. Can you make a hidden eleanor subdirectory in your home directory

`mkdir ~/.eleanor`

and re-run and see if that changes things?

**Comment by rachelbf** [comment]
The kernel indeed crashes at the eleanor.TargetData cell. When I create the hidden subdirectory, it still seems to give me the same issue. Now the kernel crashes without any errors around the same place
![Screen Shot 2019-03-22 at 2 19 15 PM](https://user-images.githubusercontent.com/48811452/54853578-7f482b00-4cad-11e9-96ae-f3d9cf90b9ad.png)
.

**Comment by afeinstein20** [comment]
Hi @rachelbf ! Sorry for not responding sooner. Would you mind trying this in a text editor/terminal? I'm wondering if it also crashes if you do it outside of a Jupyter notebook. Let me know how that goes!
