### ISSUE TITLE
Detector corners

### ISSUE THREAD

**Issue by benmontet** [afeinstein20/eleanor#76]
If someone (me) tries to make a TPF, and the TPF would extend beyond the edge of the detector, there is an error in trying to match up sizes of things.

This worked at one point, so recent changes must have messed up our previous fix somehow.

Example: tic 79015293 in sector 1.

**Comment by afeinstein20** [comment]
Can you post a screenshot of the actual error you're getting?

**Comment by benmontet** [comment]
The issue is here:

```
  File "/home/bmontet/eleanordata/targetdata.py", line 437, in get_lightcurve
    flat_lc_tpf = lc_obj_tpf.flatten(polyorder=2, window_length=51)
  File "/home/bmontet/.local/lib/python3.4/site-packages/lightkurve/lightcurve.py", line 351, in flatten
    f = interp1d(self.time[mask][mask1], trend_signal[mask1], fill_value='extrapolate')
  File "/usr/lib64/python3.4/site-packages/scipy/interpolate/interpolate.py", line 444, in __init__
    self._y = self._reshape_yi(self.y)
  File "/usr/lib64/python3.4/site-packages/scipy/interpolate/polyint.py", line 111, in _reshape_yi
    return yi.reshape((yi.shape[0], -1))
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
```

The function that was once called jitter_corr is getting passed through a list of nans, because the flux array that is defined for it to receive (all_corr_lc_tpf_sub[a]) is all zeros (divided by nanmedian of zero), because that is set in a try-except call, and that is failing because it's trying to multiply together two things, one of shape (11,13) and another of shape (13,13)

**Comment by benmontet** [comment]
This is very closely related to issue #68.

**Comment by afeinstein20** [comment]
This issue was caused by us trimming in one direction (wherever the edge was) and not adding to the opposite side, to ensure the shape of the TPF is (13,13). I killed this bug with a newspaper this morning.
