### ISSUE TITLE
Problem with tutorial: "FFIINDEX does not exist"

### ISSUE THREAD

**Issue by kristalynne** [afeinstein20/eleanor#88]
Hi! I have just downloaded eleanor via pip3 and am running iPython with version 3.7.3. When I attempt the data = eleanor.TargetData step of the tutorial, I receive the following errors:

<img width="829" alt="Screen Shot 2019-06-21 at 10 07 56 AM" src="https://user-images.githubusercontent.com/47906409/59939332-81389c00-940c-11e9-8a5f-716d482f1f84.png">

Any thoughts?

**Comment by afeinstein20** [comment]
Hi @kristalynne ! Can you please post the actual script you are running to get this error? A screenshot would also be fine :) I think I have an idea of what's going on, but I just want to double check. Thanks!

**Comment by kristalynne** [comment]
Sure! Here are the commands just before the error:
<img width="1216" alt="Screen Shot 2019-06-21 at 10 13 27 AM" src="https://user-images.githubusercontent.com/47906409/59939609-57cc4000-940d-11e9-96fe-294f663e709c.png">

**Comment by afeinstein20** [comment]
Great, thanks! If you call:
star = eleanor.Source(tic=38846515, sector=1, **tc=True**)
data = eleanor.TargetData(star, height=15, width=15, bkg_size=31, do_psf=True, do_pca=True)
this should solve your issue!

The argument **tc=True** is a recent development which wraps over TessCut to give users access to Sectors 1-11 while we continue to test new background removal methods for the eleanor postcards. If this fix works, please close the issue :) Thanks!

**Comment by kristalynne** [comment]
Thanks, the TargetData call now works!
