### ISSUE TITLE
Visualizing Postcards

### ISSUE THREAD

**Issue by kristalynne** [afeinstein20/eleanor#89]
Hello again!

The documentation says that eleanor.Visualize "allows for plotting of both postcards and tpfs." However, I have just tried to create a postcard object (the same star from the tutorial) and open it with Visualize, and received this error: 'Postcard' object has no attribute 'tpf'.

Here is a screenshot:

<img width="989" alt="Screen Shot 2019-06-21 at 12 06 53 PM" src="https://user-images.githubusercontent.com/47906409/59945661-1e033580-941d-11e9-88f1-9d7e1141a3a8.png">

I am trying to gear up to use the custom aperture pixel selection tool, but can't figure out what I'm supposed to load into it to select the pixels!

Thank you!

**Comment by afeinstein20** [comment]
Hey @kristalynne ! Which function within Visualize are you trying to use?
