### ISSUE TITLE
Move postcard background images to seperate files

### ISSUE THREAD

**Issue by dfm** [afeinstein20/eleanor#94]
Since we're using a post processing step to compute the backgrounds, it's probably better to save them as a separate file so we don't risk corrupting the generated postcards. How do y'all feel about that as an option? It would change the user code a bit but perhaps not too much?

**Comment by afeinstein20** [comment]
I think that's fine! As long as they have similar naming conventions so we're aware of which background goes with which postcard, it shouldn't be too hard to fix that up.

**Comment by dfm** [comment]
Sounds good. I'll set that up to go for the next run unless there are other concerns
