### ISSUE TITLE
eleanor.Source() Not working

### ISSUE THREAD

**Issue by ngalliher** [afeinstein20/eleanor#95]
I am trying to find a star using eleanor.Source(coords = (), sector =  , tc = True), and Python is returning an attribute error:
 'AttributeError: module 'eleanor' has no attribute 'Source' '
I updated the eleanor module, so my version should be current. Not sure what the problem is?

**Comment by afeinstein20** [comment]
Hi @ngalliher ! Can you please send a screenshot of your script? This would help when debugging the issue. Thanks!

**Comment by ngalliher** [comment]
Hi, 
Yes here it is!
<img width="753" alt="eleanor_script" src="https://user-images.githubusercontent.com/51929705/60276088-fbfc2e00-98c8-11e9-87bf-df18da997e3a.png">

**Comment by afeinstein20** [comment]
Hmmm, can you please print out eleanor.__version__ and eleanor.__path__?

**Comment by benmontet** [comment]
Hi @ngalliher,

Did you install through pip or from github? What is your working directory that you're calling it from? I believe you will run into issues if you're trying to call it from the directory in which it's installed, but I don't deeply understand how all that works.

Can you also verify that in your eleanor directory you have a file called eleanor/__init__.py?

**Comment by ngalliher** [comment]
Hi, 
Sorry for the late reply. I figured out my issue, it was a simple user error. Thank you for your help!

**Comment by benmontet** [comment]
Great! What was the issue out of curiosity? It will help give us an idea what to suggest next time someone has the same issue (or when they google and find themselves here!)
