### ISSUE TITLE
Cache directory?

### ISSUE THREAD

**Issue by dfm** [afeinstein20/eleanor#96]
@nksaunders: what's the deal with the `.cache/v/cache` directory? Apparently you added it, but I'm not sure what it's there for...

**Comment by nksaunders** [comment]
That's the cache for `pytest`, which I set up. It contains a file of `lastfailed` tests, allowing you to call `pytest --lf` to only run the most recently failing tests.

We can delete it, and I believe adding `-p no:cacheprovider` to [this line](https://github.com/afeinstein20/eleanor/blob/4438875163f434c1f167e7f3f1720576a1ea1523/.travis.yml#L41) will prevent it from being created when tests are called by travis.

**Comment by dfm** [comment]
It was last updated in March so it's not clear to me what it adds... I don't think we need to add `-p no:cacheprovider`. Travis doesn't commit anything back to the repo so what travis generates doesn't matter!

**Comment by nksaunders** [comment]
Yep, good point. Opened a [PR](https://github.com/afeinstein20/eleanor/pull/97) to remove it.
